# Generated by Django 5.2.8 on 2026-03-08 13:13

import django.db.models.deletion
from importlib import import_module
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# clubs.migrations.0001_initial


def _initial_module():
    return import_module('clubs.migrations.0001_initial')


def populate_departments(apps, schema_editor):
    _initial_module().populate_departments(apps, schema_editor)


def populate_requirements(apps, schema_editor):
    _initial_module().populate_requirements(apps, schema_editor)


def reverse_func(apps, schema_editor):
    _initial_module().reverse_func(apps, schema_editor)

class Migration(migrations.Migration):

    replaces = [('clubs', '0001_initial'), ('clubs', '0002_clubmember_inactiveextensionhistory_and_more'), ('clubs', '0003_registrationtoken_max_uses_and_more'), ('clubs', '0004_activityapplication_is_public_activityregistration')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='社团名称')),
                ('description', models.TextField(blank=True, verbose_name='社团介绍')),
                ('founded_date', models.DateField(verbose_name='成立日期')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃'), ('suspended', '停止')], default='active', max_length=20, verbose_name='状态')),
                ('members_count', models.IntegerField(default=0, verbose_name='成员数')),
                ('review_enabled', models.BooleanField(default=False, verbose_name='是否开启年审')),
                ('registration_enabled', models.BooleanField(default=False, verbose_name='是否开启注册')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '社团',
                'verbose_name_plural': '社团',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='访问次数')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('annual_review', '社团年审'), ('club_registration', '社团注册'), ('club_application', '社团申请'), ('president_transition', '社长换届'), ('reimbursement', '报销申请'), ('activity_application', '活动申请')], max_length=50, verbose_name='申请类型')),
                ('name', models.CharField(max_length=200, verbose_name='材料名称')),
                ('description', models.TextField(blank=True, verbose_name='材料描述')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('allowed_extensions', models.CharField(default='.docx,.pdf,.jpg,.png,.zip', max_length=200, verbose_name='允许的文件扩展名')),
                ('max_size_mb', models.IntegerField(default=10, verbose_name='最大文件大小(MB)')),
                ('order', models.IntegerField(default=0, verbose_name='排序权重')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('legacy_field_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='旧字段名')),
                ('template_file', models.FileField(blank=True, help_text='供用户下载的模板文件', null=True, upload_to='templates/', verbose_name='模板文件')),
                ('icon', models.CharField(default='cloud_upload', help_text='Material Icons 图标名称', max_length=50, verbose_name='图标')),
            ],
            options={
                'verbose_name': '材料要求',
                'verbose_name_plural': '材料要求',
                'ordering': ['request_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='房间名称')),
                ('capacity', models.IntegerField(default=50, verbose_name='容纳人数')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('available', '可用'), ('maintenance', '维护中'), ('closed', '关闭')], default='available', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_icon_url', models.CharField(default='https://fonts.font.im/icon?family=Material+Icons', help_text='Material Icons CSS 的完整 URL，修改后刷新页面生效', max_length=500, verbose_name='图标字体 CSS 地址')),
                ('body_font_url', models.CharField(blank=True, default='', help_text='Google Fonts / 镜像字体的 CSS URL（留空则不加载额外字体）', max_length=500, verbose_name='正文 Web 字体 CSS 地址')),
                ('body_font_family', models.CharField(blank=True, default='', help_text="CSS font-family 值，例如：'Noto Sans SC', sans-serif（留空则使用系统字体）", max_length=300, verbose_name='正文字体族')),
            ],
            options={
                'verbose_name': '站点设置',
                'verbose_name_plural': '站点设置',
            },
        ),
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('qq', 'QQ邮箱'), ('163', '163邮箱'), ('outlook', 'Outlook'), ('gmail', 'Gmail'), ('custom', '自定义')], max_length=20, verbose_name='邮箱服务商')),
                ('smtp_host', models.CharField(max_length=100, verbose_name='SMTP服务器地址')),
                ('smtp_port', models.IntegerField(verbose_name='SMTP端口')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='发送邮箱地址')),
                ('sender_password', models.CharField(help_text='某些邮箱需要使用授权码而非密码', max_length=255, verbose_name='邮箱密码/授权码')),
                ('use_tls', models.BooleanField(default=True, verbose_name='是否使用TLS加密')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'SMTP配置',
                'verbose_name_plural': 'SMTP配置',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('label', models.CharField(max_length=50, verbose_name='显示名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '时间段',
                'verbose_name_plural': '时间段',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200, verbose_name='活动名称')),
                ('activity_type', models.CharField(choices=[('academic', '学术类'), ('cultural', '文化类'), ('sports', '体育类'), ('volunteer', '志愿类'), ('entertainment', '娱乐类'), ('other', '其他')], default='other', max_length=20, verbose_name='活动类型')),
                ('activity_description', models.TextField(verbose_name='活动描述')),
                ('activity_date', models.DateField(verbose_name='活动日期')),
                ('activity_time_start', models.TimeField(verbose_name='活动开始时间')),
                ('activity_time_end', models.TimeField(verbose_name='活动结束时间')),
                ('activity_location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('expected_participants', models.IntegerField(verbose_name='预计参与人数')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='活动预算')),
                ('application_form', models.FileField(help_text='支持上传Word文档(.docx)或PDF文件(.pdf)', upload_to='activity_application/%Y/%m/', verbose_name='活动申请表')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('staff_approved', '干事已批准'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('staff_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='干事审核时间')),
                ('staff_comment', models.TextField(blank=True, verbose_name='干事审核意见')),
                ('staff_approved', models.BooleanField(blank=True, null=True, verbose_name='干事是否批准')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('is_read', models.BooleanField(default=False, verbose_name='社长是否已读')),
                ('resubmission_attempt', models.IntegerField(default=1, verbose_name='提交次数')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activities', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('staff_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_reviewed_activities', to=settings.AUTH_USER_MODEL, verbose_name='干事审核人')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_applications', to='clubs.club', verbose_name='社团')),
            ],
            options={
                'verbose_name': '活动申请',
                'verbose_name_plural': '活动申请',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(verbose_name='提交次数')),
                ('activity_name', models.CharField(max_length=200, verbose_name='活动名称')),
                ('activity_date', models.DateField(verbose_name='活动日期')),
                ('submitted_at', models.DateTimeField(verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('staff_approved', '干事已批准'), ('approved', '已批准'), ('rejected', '被拒绝')], max_length=20, verbose_name='状态')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('activity_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='clubs.activityapplication', verbose_name='关联活动申请')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_history_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '活动申请审核历史',
                'verbose_name_plural': '活动申请审核历史',
                'ordering': ['-attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='ClubRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_form', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团注册申请表')),
                ('basic_info_form', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='学生社团基础信息表')),
                ('membership_fee_form', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='会费表或免收会费说明书')),
                ('leader_change_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团主要负责人变动申请')),
                ('meeting_minutes', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团大会会议记录')),
                ('name_change_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团名称变更申请表')),
                ('advisor_change_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团指导老师变动申请表')),
                ('business_advisor_change_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团业务指导单位变动申请表')),
                ('new_media_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='新媒体平台建立申请表')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('is_read', models.BooleanField(default=False, verbose_name='社长是否已读')),
                ('resubmission_attempt', models.IntegerField(default=1, verbose_name='提交次数')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='clubs.club', verbose_name='社团')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '社团注册',
                'verbose_name_plural': '社团注册',
            },
        ),
        migrations.CreateModel(
            name='ClubRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, verbose_name='社团名称')),
                ('description', models.TextField(verbose_name='社团介绍')),
                ('founded_date', models.DateField(verbose_name='成立日期')),
                ('members_count', models.IntegerField(verbose_name='成员数')),
                ('president_name', models.CharField(max_length=100, verbose_name='社长名字')),
                ('president_id', models.CharField(max_length=20, verbose_name='社长学号')),
                ('president_email', models.EmailField(max_length=254, verbose_name='社长邮箱')),
                ('establishment_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团成立申请书')),
                ('constitution_draft', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团章程草案')),
                ('three_year_plan', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团三年发展规划')),
                ('leaders_resumes', models.FileField(blank=True, help_text='支持上传压缩包(.zip, .rar)或Word文档(.docx)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团拟任负责人和指导老师的详细简历和身份证复印件')),
                ('one_month_activity_plan', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团组建一个月后的活动计划')),
                ('advisor_certificates', models.FileField(blank=True, help_text='支持上传压缩包(.zip, .rar)或图片文件(.jpg, .png)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团老师的相关专业证书')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('is_read', models.BooleanField(default=False, verbose_name='社长是否已读')),
                ('resubmission_attempt', models.IntegerField(default=1, verbose_name='提交次数')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_club_registrations', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '社团注册申请',
                'verbose_name_plural': '社团注册申请',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubApplicationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝')], max_length=20, verbose_name='审核结果')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('submission_attempt', models.IntegerField(default=1, verbose_name='提交次数')),
                ('rejected_materials', models.JSONField(blank=True, default=list, verbose_name='被拒绝的材料')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clubs.clubregistrationrequest', verbose_name='社团申请')),
            ],
            options={
                'verbose_name': '社团申请审核记录',
                'verbose_name_plural': '社团申请审核记录',
            },
        ),
        migrations.CreateModel(
            name='ClubRegistrationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝')], max_length=20, verbose_name='审核结果')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('submission_attempt', models.IntegerField(default=1, verbose_name='提交次数')),
                ('rejected_materials', models.JSONField(blank=True, default=list, verbose_name='被拒绝的材料')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clubs.clubregistration', verbose_name='社团注册')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '社团注册审核记录',
                'verbose_name_plural': '社团注册审核记录',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='部门名称')),
                ('description', models.TextField(verbose_name='职责描述')),
                ('highlights', models.TextField(blank=True, help_text='多个重点工作用换行分隔', verbose_name='重点工作')),
                ('icon', models.CharField(default='work', help_text='Material Icons图标名称', max_length=50, verbose_name='图标名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='待验证邮箱')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('president', '社长')], max_length=20, verbose_name='职位')),
                ('appointed_date', models.DateField(verbose_name='任命日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_current', models.BooleanField(default=True, verbose_name='是否现任')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='clubs.club', verbose_name='社团')),
            ],
            options={
                'verbose_name': '社团干部',
                'verbose_name_plural': '社团干部',
                'ordering': ['-appointed_date'],
            },
        ),
        migrations.CreateModel(
            name='PresidentTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_date', models.DateField(verbose_name='换届日期')),
                ('transition_reason', models.TextField(verbose_name='换届原因')),
                ('transition_form', models.FileField(help_text='支持上传Word文档(.docx)或PDF文件(.pdf)', upload_to='president_transition/%Y/%m/', verbose_name='社团主要负责人变动申请表')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('is_read', models.BooleanField(default=False, verbose_name='社长是否已读')),
                ('resubmission_attempt', models.IntegerField(default=1, verbose_name='提交次数')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president_transitions', to='clubs.club', verbose_name='社团')),
                ('new_president_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='clubs.officer', verbose_name='新社长干部记录')),
                ('old_president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to=settings.AUTH_USER_MODEL, verbose_name='原社长')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transitions', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '社长换届申请',
                'verbose_name_plural': '社长换届申请',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationPeriod',
            fields=[
                ('period_number', models.AutoField(primary_key=True, serialize=False, verbose_name='周期编号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '社团注册周期',
                'verbose_name_plural': '社团注册周期',
                'ordering': ['-period_number'],
            },
        ),
        migrations.AddField(
            model_name='clubregistration',
            name='registration_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='clubs.registrationperiod', verbose_name='注册周期'),
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(verbose_name='报销日期')),
                ('reimbursement_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='报销金额')),
                ('description', models.TextField(verbose_name='报销说明')),
                ('receipt_file', models.FileField(upload_to='reimbursements/%Y/%m/', verbose_name='报销凭证')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('is_read', models.BooleanField(default=False, verbose_name='社长是否已读')),
                ('resubmission_attempt', models.IntegerField(default=1, verbose_name='提交次数')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='clubs.club', verbose_name='社团')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reimbursements', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '报销材料',
                'verbose_name_plural': '报销材料',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReimbursementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(verbose_name='提交次数')),
                ('submission_date', models.DateField(verbose_name='报销日期')),
                ('reimbursement_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='报销金额')),
                ('description', models.TextField(verbose_name='报销说明')),
                ('submitted_at', models.DateTimeField(verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], max_length=20, verbose_name='状态')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reimbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='clubs.reimbursement', verbose_name='关联报销')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursement_history_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '报销审核历史',
                'verbose_name_plural': '报销审核历史',
                'ordering': ['-attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_year', models.IntegerField(verbose_name='提交年份')),
                ('self_assessment_form', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='自查表')),
                ('club_constitution', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='社团章程')),
                ('leader_learning_work_report', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='负责人学习及工作情况表')),
                ('annual_activity_list', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='社团年度活动清单')),
                ('advisor_performance_report', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='指导教师履职情况表')),
                ('financial_report', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='年度财务情况表')),
                ('member_composition_list', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='社团成员构成表')),
                ('new_media_account_report', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='新媒体账号及运维情况表')),
                ('other_materials', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='其他材料')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后审核时间')),
                ('review_count', models.IntegerField(default=0, verbose_name='审核次数')),
                ('is_read_by_president', models.BooleanField(default=False, verbose_name='社长是否已读')),
                ('resubmission_attempt', models.IntegerField(default=1, verbose_name='提交次数')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_submissions', to='clubs.club', verbose_name='社团')),
            ],
            options={
                'verbose_name': '年审材料',
                'verbose_name_plural': '年审材料',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='借用日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('purpose', models.TextField(verbose_name='借用目的')),
                ('participant_count', models.IntegerField(verbose_name='预计使用人数')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('special_requirements', models.TextField(blank=True, help_text='如需要投影仪、音响等设备', verbose_name='特殊需求')),
                ('status', models.CharField(choices=[('active', '有效'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_bookings', to='clubs.club', verbose_name='所属社团')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clubs.room', verbose_name='房间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to=settings.AUTH_USER_MODEL, verbose_name='借用人')),
            ],
            options={
                'verbose_name': '房间借用',
                'verbose_name_plural': '房间借用',
                'ordering': ['booking_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝')], max_length=20, verbose_name='审核结果')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('submission_attempt', models.IntegerField(default=1, verbose_name='提交次数')),
                ('rejected_materials', models.JSONField(blank=True, default=list, verbose_name='被拒绝的材料')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clubs.reviewsubmission', verbose_name='年审材料')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmittedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/%Y/%m/', verbose_name='文件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.materialrequirement', verbose_name='对应材料要求')),
            ],
            options={
                'verbose_name': '提交文件',
                'verbose_name_plural': '提交文件',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('review_financial', '年审 - 财务报告'), ('review_activity', '年审 - 活动报告'), ('review_member_list', '年审 - 成员名单'), ('review_self_assessment', '年审 - 自查表'), ('review_club_constitution', '年审 - 社团章程'), ('review_leader_report', '年审 - 负责人学习及工作情况表'), ('review_annual_activity', '年审 - 社团年度活动清单'), ('review_advisor_report', '年审 - 指导教师履职情况表'), ('review_member_composition', '年审 - 社团成员构成表'), ('review_media_account', '年审 - 新媒体账号及运维情况表'), ('reimbursement', '报销模板'), ('application_establishment', '社团申请 - 社团成立申请书'), ('application_constitution', '社团申请 - 社团章程草案'), ('application_three_year_plan', '社团申请 - 社团三年发展规划'), ('application_leader_resume', '社团申请 - 负责人简历'), ('application_advisor_resume', '社团申请 - 指导老师简历'), ('application_id_copies', '社团申请 - 身份证复印件'), ('application_monthly_plan', '社团申请 - 一个月活动计划'), ('application_teacher_certificates', '社团申请 - 指导老师专业证书'), ('registration_form', '社团注册 - 社团注册申请表'), ('registration_basic_info', '社团注册 - 学生社团基础信息表'), ('registration_fee_form', '社团注册 - 会费表'), ('registration_fee_exemption', '社团注册 - 免收会费说明书'), ('registration_leader_change', '社团注册 - 负责人变动申请'), ('registration_meeting_minutes', '社团注册 - 社团大会会议记录'), ('registration_name_change', '社团注册 - 社团名称变更申请表'), ('registration_advisor_change', '社团注册 - 指导老师变动申请表'), ('registration_business_unit_change', '社团注册 - 业务指导单位变动申请表'), ('registration_social_media', '社团注册 - 新媒体平台建立申请表'), ('club_creation', '社团创建文件'), ('leader_change', '社长变更申请')], max_length=50, verbose_name='模板类型')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('file', models.FileField(upload_to='templates/%Y/%m/', verbose_name='模板文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '模板',
                'verbose_name_plural': '模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('president', '社长'), ('staff', '干事'), ('admin', '管理员')], default='president', max_length=20, verbose_name='角色')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝')], default='approved', max_length=20, verbose_name='状态')),
                ('department', models.CharField(blank=True, max_length=20, null=True, verbose_name='部门')),
                ('staff_level', models.CharField(choices=[('member', '部员'), ('director', '部长')], default='member', help_text='仅对干事有效', max_length=20, verbose_name='部员/部长')),
                ('real_name', models.CharField(blank=True, max_length=100, verbose_name='真名')),
                ('student_id', models.CharField(blank=True, max_length=50, verbose_name='学号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('wechat', models.CharField(blank=True, max_length=100, verbose_name='微信')),
                ('political_status', models.CharField(choices=[('communist_party_member', '中共党员'), ('communist_party_probationary', '中共预备党员'), ('communist_youth_league', '共青团员'), ('revolutionary_committee', '民革党员'), ('china_democratic_league', '民盟盟员'), ('democratic_national_construction', '民建会员'), ('china_peasants_workers_democratic', '农工党党员'), ('china_council_for_promoting', '致公党党员'), ('jiusanshe', '九三学社社员'), ('taiwan_democratic_self_government', '台盟盟员'), ('non_party_personage', '无党派人士'), ('progressive', '入党积极分子'), ('non_member', '群众')], default='non_member', max_length=40, verbose_name='政治面貌')),
                ('is_info_public', models.BooleanField(default=False, verbose_name='是否公开个人信息')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='是否需要修改密码')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='头像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='clubs.department', verbose_name='关联部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
            },
        ),
        migrations.CreateModel(
            name='StaffClubRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_staff', to='clubs.club', verbose_name='社团')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_clubs', to='clubs.userprofile', verbose_name='干事')),
            ],
            options={
                'verbose_name': '干事负责社团',
                'verbose_name_plural': '干事负责社团',
            },
        ),
        migrations.AddField(
            model_name='officer',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.userprofile', verbose_name='用户信息'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/%Y/%m/', verbose_name='附件')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='ann_status_pub_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='轮播图片')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('link', models.URLField(blank=True, help_text='点击轮播图跳转的地址', verbose_name='跳转链接')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '轮播图片',
                'verbose_name_plural': '轮播图片',
                'ordering': ['order', '-uploaded_at'],
                'indexes': [models.Index(fields=['is_active', 'order', '-uploaded_at'], name='carousel_active_ord_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='activityapplication',
            index=models.Index(fields=['club', 'status', '-submitted_at'], name='aa_club_status_idx'),
        ),
        migrations.AddIndex(
            model_name='activityapplication',
            index=models.Index(fields=['status', '-reviewed_at'], name='aa_status_reviewed_idx'),
        ),
        migrations.AddIndex(
            model_name='activityapplication',
            index=models.Index(fields=['staff_approved', '-submitted_at'], name='aa_staff_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='clubregistrationrequest',
            index=models.Index(fields=['requested_by', 'status', '-submitted_at'], name='crr_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clubregistrationrequest',
            index=models.Index(fields=['status', '-reviewed_at'], name='crr_status_reviewed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clubapplicationreview',
            unique_together={('application', 'reviewer', 'submission_attempt')},
        ),
        migrations.AlterUniqueTogether(
            name='clubregistrationreview',
            unique_together={('registration', 'reviewer', 'submission_attempt')},
        ),
        migrations.AddIndex(
            model_name='presidenttransition',
            index=models.Index(fields=['club', 'status', '-submitted_at'], name='pt_club_status_idx'),
        ),
        migrations.AddIndex(
            model_name='presidenttransition',
            index=models.Index(fields=['status', '-reviewed_at'], name='pt_status_reviewed_idx'),
        ),
        migrations.AddIndex(
            model_name='clubregistration',
            index=models.Index(fields=['club', 'status', '-submitted_at'], name='cr_club_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clubregistration',
            index=models.Index(fields=['status', '-reviewed_at'], name='cr_status_reviewed_idx'),
        ),
        migrations.AddIndex(
            model_name='reimbursement',
            index=models.Index(fields=['club', 'status', '-submitted_at'], name='reimb_club_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reimbursement',
            index=models.Index(fields=['status', '-reviewed_at'], name='reimb_status_reviewed_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewsubmission',
            index=models.Index(fields=['club', 'status', '-submitted_at'], name='rsub_club_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewsubmission',
            index=models.Index(fields=['status', '-reviewed_at'], name='rsub_status_reviewed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewsubmission',
            unique_together={('club', 'submission_year')},
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['room', 'booking_date', 'status'], name='rb_room_date_idx'),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['user', 'booking_date'], name='rb_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['club', 'booking_date'], name='rb_club_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='roombooking',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='room_end_time_after_start_time'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionreview',
            unique_together={('submission', 'reviewer', 'submission_attempt')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role', 'status'], name='up_role_status_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role', 'staff_level'], name='up_role_staff_lvl_idx'),
        ),
        migrations.AddIndex(
            model_name='staffclubrelation',
            index=models.Index(fields=['staff', 'is_active'], name='scr_staff_active_idx'),
        ),
        migrations.AddIndex(
            model_name='staffclubrelation',
            index=models.Index(fields=['club', 'is_active'], name='scr_club_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffclubrelation',
            unique_together={('staff', 'club')},
        ),
        migrations.AddIndex(
            model_name='officer',
            index=models.Index(fields=['user_profile', 'position', 'is_current'], name='officer_user_pos_cur_idx'),
        ),
        migrations.AddIndex(
            model_name='officer',
            index=models.Index(fields=['club', 'position', 'is_current'], name='officer_club_pos_cur_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='officer',
            unique_together={('club', 'user_profile', 'position')},
        ),
        migrations.RunPython(
            code=populate_departments,
            reverse_code=reverse_func,
        ),
        migrations.RunPython(
            code=populate_requirements,
            reverse_code=reverse_func,
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃')], default='active', max_length=20, verbose_name='成员状态')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '社团成员',
                'verbose_name_plural': '社团成员',
            },
        ),
        migrations.CreateModel(
            name='InactiveExtensionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extended_at', models.DateTimeField(auto_now_add=True, verbose_name='延期时间')),
                ('previous_active_until', models.DateTimeField(blank=True, null=True, verbose_name='延期前有效期')),
                ('new_active_until', models.DateTimeField(verbose_name='延期后有效期')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='延期原因')),
            ],
            options={
                'verbose_name': '不活跃延期记录',
                'verbose_name_plural': '不活跃延期记录',
                'ordering': ['-extended_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='一次性校验码')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '社员注册令牌',
                'verbose_name_plural': '社员注册令牌',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_status',
            field=models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃')], default='active', max_length=20, verbose_name='账号活跃状态'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='活跃有效期至'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=models.CharField(blank=True, max_length=100, verbose_name='学院'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inactive_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='不活跃起始时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qq',
            field=models.CharField(blank=True, max_length=30, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('president', '社长'), ('member', '社员'), ('staff', '干事'), ('admin', '管理员')], default='president', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('inactive', '不活跃')], default='approved', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['account_status', 'inactive_since'], name='up_acc_inactive_idx'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.club', verbose_name='社团'),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='clubs.userprofile', verbose_name='成员'),
        ),
        migrations.AddField(
            model_name='inactiveextensionhistory',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inactive_extensions', to='clubs.userprofile', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='registrationtoken',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_tokens', to='clubs.club', verbose_name='社团'),
        ),
        migrations.AddField(
            model_name='registrationtoken',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_registration_tokens', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddIndex(
            model_name='clubmember',
            index=models.Index(fields=['club', 'status'], name='cm_club_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clubmember',
            index=models.Index(fields=['user_profile', 'status'], name='cm_user_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clubmember',
            unique_together={('club', 'user_profile')},
        ),
        migrations.AddIndex(
            model_name='registrationtoken',
            index=models.Index(fields=['club', 'expires_at', 'is_used'], name='rt_club_exp_used_idx'),
        ),
        migrations.AddField(
            model_name='registrationtoken',
            name='max_uses',
            field=models.IntegerField(blank=True, null=True, verbose_name='最大使用次数（null表示不限次数）'),
        ),
        migrations.AddField(
            model_name='registrationtoken',
            name='used_count',
            field=models.IntegerField(default=0, verbose_name='已使用次数'),
        ),
        migrations.AddField(
            model_name='activityapplication',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='clubs.activityapplication', verbose_name='活动')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_registrations', to='clubs.userprofile', verbose_name='报名用户')),
            ],
            options={
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名',
                'unique_together': {('activity', 'user_profile')},
            },
        ),
    ]
