# Generated by Django 5.2.8 on 2025-11-26 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='社团名称')),
                ('description', models.TextField(blank=True, verbose_name='社团介绍')),
                ('founded_date', models.DateField(verbose_name='成立日期')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃'), ('suspended', '停止')], default='active', max_length=20, verbose_name='状态')),
                ('members_count', models.IntegerField(default=0, verbose_name='成员数')),
                ('review_enabled', models.BooleanField(default=False, verbose_name='是否开启年审')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_as_president', to=settings.AUTH_USER_MODEL, verbose_name='社长账户')),
            ],
            options={
                'verbose_name': '社团',
                'verbose_name_plural': '社团',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubInfoChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name', models.CharField(blank=True, max_length=100, verbose_name='新社团名称')),
                ('new_description', models.TextField(blank=True, verbose_name='新社团介绍')),
                ('new_members_count', models.IntegerField(blank=True, null=True, verbose_name='新成员数')),
                ('change_reason', models.TextField(verbose_name='变更原因')),
                ('supporting_document', models.FileField(blank=True, upload_to='club_info_changes/%Y/%m/', verbose_name='支持文件')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_change_requests', to='clubs.club', verbose_name='社团')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '社团信息修改申请',
                'verbose_name_plural': '社团信息修改申请',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, verbose_name='社团名称')),
                ('description', models.TextField(verbose_name='社团介绍')),
                ('founded_date', models.DateField(verbose_name='成立日期')),
                ('members_count', models.IntegerField(default=0, verbose_name='成员数')),
                ('president_name', models.CharField(max_length=100, verbose_name='社长名字')),
                ('president_id', models.CharField(max_length=20, verbose_name='社长学号')),
                ('president_email', models.EmailField(max_length=254, verbose_name='社长邮箱')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '社团注册申请',
                'verbose_name_plural': '社团注册申请',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaderChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_leader_name', models.CharField(max_length=100, verbose_name='原社长名字')),
                ('old_leader_id', models.CharField(max_length=20, verbose_name='原社长学号')),
                ('new_leader_name', models.CharField(max_length=100, verbose_name='新社长名字')),
                ('new_leader_id', models.CharField(max_length=20, verbose_name='新社长学号')),
                ('change_reason', models.TextField(verbose_name='变更原因')),
                ('attachment', models.FileField(blank=True, upload_to='leader_changes/%Y/%m/', verbose_name='证明附件')),
                ('gpa_proof', models.FileField(blank=True, upload_to='leader_changes/%Y/%m/', verbose_name='学习绩点证明')),
                ('ranking_proof', models.FileField(blank=True, upload_to='leader_changes/%Y/%m/', verbose_name='年级排名证明')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_changes', to='clubs.club', verbose_name='社团')),
            ],
            options={
                'verbose_name': '社长变更',
                'verbose_name_plural': '社长变更',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(verbose_name='报销日期')),
                ('reimbursement_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='报销金额')),
                ('description', models.TextField(verbose_name='报销说明')),
                ('receipt_file', models.FileField(upload_to='reimbursements/%Y/%m/', verbose_name='收据/发票')),
                ('proof_document', models.FileField(upload_to='reimbursements/%Y/%m/', verbose_name='支持文件')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='clubs.club', verbose_name='社团')),
            ],
            options={
                'verbose_name': '报销材料',
                'verbose_name_plural': '报销材料',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('review_financial', '年审 - 财务报告'), ('review_activity', '年审 - 活动报告'), ('review_member_list', '年审 - 成员名单'), ('reimbursement', '报销模板'), ('club_creation', '社团创建文件')], max_length=30, verbose_name='模板类型')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('file', models.FileField(upload_to='templates/%Y/%m/', verbose_name='模板文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '模板',
                'verbose_name_plural': '模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('president', '社长'), ('staff', '干事'), ('admin', '管理员')], default='president', max_length=20, verbose_name='角色')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝')], default='approved', max_length=20, verbose_name='状态')),
                ('real_name', models.CharField(blank=True, max_length=100, verbose_name='真名')),
                ('student_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='学号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('wechat', models.CharField(blank=True, max_length=100, verbose_name='微信')),
                ('political_status', models.CharField(choices=[('party_member', '党员'), ('league_member', '团员'), ('progressive', '入党积极分子'), ('non_member', '群众')], default='non_member', max_length=20, verbose_name='政治面貌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
            },
        ),
        migrations.CreateModel(
            name='ReviewSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_year', models.IntegerField(verbose_name='提交年份')),
                ('financial_report', models.FileField(upload_to='reviews/%Y/%m/', verbose_name='财务报告')),
                ('activity_report', models.FileField(upload_to='reviews/%Y/%m/', verbose_name='活动报告')),
                ('member_list', models.FileField(upload_to='reviews/%Y/%m/', verbose_name='成员名单')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_submissions', to='clubs.club', verbose_name='社团')),
            ],
            options={
                'verbose_name': '年审材料',
                'verbose_name_plural': '年审材料',
                'ordering': ['-submitted_at'],
                'unique_together': {('club', 'submission_year')},
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('president', '社长'), ('vice_president', '副社长'), ('secretary', '秘书'), ('treasurer', '财务'), ('member', '普通成员')], max_length=20, verbose_name='职位')),
                ('appointed_date', models.DateField(verbose_name='任命日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_current', models.BooleanField(default=True, verbose_name='是否现任')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='clubs.club', verbose_name='社团')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.userprofile', verbose_name='用户信息')),
            ],
            options={
                'verbose_name': '社团干部',
                'verbose_name_plural': '社团干部',
                'ordering': ['-appointed_date'],
                'unique_together': {('club', 'user_profile', 'position')},
            },
        ),
    ]
