# Generated by Django 5.2.8 on 2025-12-17 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# clubs.migrations.0001_initial

def migrate_names(apps, schema_editor):
    """迁移现有数据：将first_name和last_name合并到real_name"""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('clubs', 'UserProfile')
    
    for profile in UserProfile.objects.all():
        if not profile.real_name:
            # 如果real_name为空，则使用User的first_name和last_name
            full_name = f"{profile.user.last_name}{profile.user.first_name}".strip()
            if full_name:
                profile.real_name = full_name
                profile.save()


def reverse_migrate(apps, schema_editor):
    """反向迁移（不需要做任何事情）"""
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='社团名称')),
                ('description', models.TextField(blank=True, verbose_name='社团介绍')),
                ('founded_date', models.DateField(verbose_name='成立日期')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃'), ('suspended', '停止')], default='active', max_length=20, verbose_name='状态')),
                ('members_count', models.IntegerField(default=0, verbose_name='成员数')),
                ('review_enabled', models.BooleanField(default=False, verbose_name='是否开启年审')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs_as_president', to=settings.AUTH_USER_MODEL, verbose_name='社长账户')),
            ],
            options={
                'verbose_name': '社团',
                'verbose_name_plural': '社团',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubInfoChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name', models.CharField(blank=True, max_length=100, verbose_name='新社团名称')),
                ('new_description', models.TextField(blank=True, verbose_name='新社团介绍')),
                ('new_members_count', models.IntegerField(blank=True, null=True, verbose_name='新成员数')),
                ('change_reason', models.TextField(verbose_name='变更原因')),
                ('supporting_document', models.FileField(blank=True, upload_to='club_info_changes/%Y/%m/', verbose_name='支持文件')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_change_requests', to='clubs.club', verbose_name='社团')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '社团信息修改申请',
                'verbose_name_plural': '社团信息修改申请',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaderChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_leader_name', models.CharField(max_length=100, verbose_name='原社长名字')),
                ('old_leader_id', models.CharField(max_length=20, verbose_name='原社长学号')),
                ('new_leader_name', models.CharField(max_length=100, verbose_name='新社长名字')),
                ('new_leader_id', models.CharField(max_length=20, verbose_name='新社长学号')),
                ('change_reason', models.TextField(verbose_name='变更原因')),
                ('attachment', models.FileField(blank=True, upload_to='leader_changes/%Y/%m/', verbose_name='证明附件')),
                ('gpa_proof', models.FileField(blank=True, upload_to='leader_changes/%Y/%m/', verbose_name='学习绩点证明')),
                ('ranking_proof', models.FileField(blank=True, upload_to='leader_changes/%Y/%m/', verbose_name='年级排名证明')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_changes', to='clubs.club', verbose_name='社团')),
            ],
            options={
                'verbose_name': '社长变更',
                'verbose_name_plural': '社长变更',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(verbose_name='报销日期')),
                ('reimbursement_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='报销金额')),
                ('description', models.TextField(verbose_name='报销说明')),
                ('receipt_file', models.FileField(upload_to='reimbursements/%Y/%m/', verbose_name='收据/发票')),
                ('proof_document', models.FileField(upload_to='reimbursements/%Y/%m/', verbose_name='支持文件')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='clubs.club', verbose_name='社团')),
            ],
            options={
                'verbose_name': '报销材料',
                'verbose_name_plural': '报销材料',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('president', '社长'), ('staff', '干事'), ('admin', '管理员')], default='president', max_length=20, verbose_name='角色')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝')], default='approved', max_length=20, verbose_name='状态')),
                ('real_name', models.CharField(blank=True, max_length=100, verbose_name='真名')),
                ('student_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='学号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('wechat', models.CharField(blank=True, max_length=100, verbose_name='微信')),
                ('political_status', models.CharField(choices=[('communist_party_member', '中共党员'), ('communist_party_probationary', '中共预备党员'), ('communist_youth_league', '共青团员'), ('revolutionary_committee', '民革党员'), ('china_democratic_league', '民盟盟员'), ('democratic_national_construction', '民建会员'), ('china_peasants_workers_democratic', '农工党党员'), ('china_council_for_promoting', '致公党党员'), ('jiusanshe', '九三学社社员'), ('taiwan_democratic_self_government', '台盟盟员'), ('non_party_personage', '无党派人士'), ('progressive', '入党积极分子'), ('non_member', '群众')], default='non_member', max_length=40, verbose_name='政治面貌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('is_info_public', models.BooleanField(default=False, verbose_name='是否公开个人信息')),
            ],
            options={
                'verbose_name': '用户角色',
                'verbose_name_plural': '用户角色',
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('president', '社长'), ('vice_president', '副社长'), ('secretary', '秘书'), ('treasurer', '财务'), ('member', '普通成员')], max_length=20, verbose_name='职位')),
                ('appointed_date', models.DateField(verbose_name='任命日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_current', models.BooleanField(default=True, verbose_name='是否现任')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='clubs.club', verbose_name='社团')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.userprofile', verbose_name='用户信息')),
            ],
            options={
                'verbose_name': '社团干部',
                'verbose_name_plural': '社团干部',
                'ordering': ['-appointed_date'],
                'unique_together': {('club', 'user_profile', 'position')},
            },
        ),
        migrations.CreateModel(
            name='StaffClubRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_staff', to='clubs.club', verbose_name='社团')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_clubs', to='clubs.userprofile', verbose_name='干事')),
            ],
            options={
                'verbose_name': '干事负责社团',
                'verbose_name_plural': '干事负责社团',
                'unique_together': {('staff', 'club')},
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/%Y/%m/', verbose_name='附件')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_year', models.IntegerField(verbose_name='提交年份')),
                ('financial_report', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='年度财务情况表')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝'), ('partially_rejected', '部分拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后审核时间')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_submissions', to='clubs.club', verbose_name='社团')),
                ('advisor_performance_report', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='指导教师履职情况表')),
                ('annual_activity_list', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='社团年度活动清单')),
                ('club_constitution', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='社团章程')),
                ('leader_learning_work_report', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='负责人学习及工作情况表')),
                ('member_composition_list', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='社团成员构成表')),
                ('new_media_account_report', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='新媒体账号及运维情况表')),
                ('other_materials', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='其他材料')),
                ('self_assessment_form', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='自查表')),
                ('is_read_by_president', models.BooleanField(default=False, verbose_name='社长是否已读')),
                ('review_count', models.IntegerField(default=0, verbose_name='审核次数')),
            ],
            options={
                'verbose_name': '年审材料',
                'verbose_name_plural': '年审材料',
                'ordering': ['-submitted_at'],
                'unique_together': {('club', 'submission_year')},
            },
        ),
        migrations.CreateModel(
            name='ClubRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, verbose_name='社团名称')),
                ('description', models.TextField(verbose_name='社团介绍')),
                ('founded_date', models.DateField(verbose_name='成立日期')),
                ('members_count', models.IntegerField(verbose_name='成员数')),
                ('president_name', models.CharField(max_length=100, verbose_name='社长名字')),
                ('president_id', models.CharField(max_length=20, verbose_name='社长学号')),
                ('president_email', models.EmailField(max_length=254, verbose_name='社长邮箱')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
                ('advisor_certificates', models.FileField(blank=True, help_text='支持上传压缩包(.zip, .rar)或图片文件(.jpg, .png)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团老师的相关专业证书')),
                ('constitution_draft', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团章程草案')),
                ('establishment_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团成立申请书')),
                ('leaders_resumes', models.FileField(blank=True, help_text='支持上传压缩包(.zip, .rar)或Word文档(.docx)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团拟任负责人和指导老师的详细简历和身份证复印件')),
                ('one_month_activity_plan', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团组建一个月后的活动计划')),
                ('three_year_plan', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团三年发展规划')),
            ],
            options={
                'verbose_name': '社团注册申请',
                'verbose_name_plural': '社团注册申请',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('review_financial', '年审 - 财务报告'), ('review_activity', '年审 - 活动报告'), ('review_member_list', '年审 - 成员名单'), ('review_self_assessment', '年审 - 自查表'), ('review_club_constitution', '年审 - 社团章程'), ('review_leader_report', '年审 - 负责人学习及工作情况表'), ('review_annual_activity', '年审 - 社团年度活动清单'), ('review_advisor_report', '年审 - 指导教师履职情况表'), ('review_member_composition', '年审 - 社团成员构成表'), ('review_media_account', '年审 - 新媒体账号及运维情况表'), ('reimbursement', '报销模板'), ('application_establishment', '社团申请 - 社团成立申请书'), ('application_constitution', '社团申请 - 社团章程草案'), ('application_three_year_plan', '社团申请 - 社团三年发展规划'), ('application_leader_resume', '社团申请 - 负责人简历'), ('application_advisor_resume', '社团申请 - 指导老师简历'), ('application_id_copies', '社团申请 - 身份证复印件'), ('application_monthly_plan', '社团申请 - 一个月活动计划'), ('application_teacher_certificates', '社团申请 - 指导老师专业证书'), ('registration_form', '社团注册 - 社团注册申请表'), ('registration_basic_info', '社团注册 - 学生社团基础信息表'), ('registration_fee_form', '社团注册 - 会费表'), ('registration_fee_exemption', '社团注册 - 免收会费说明书'), ('registration_leader_change', '社团注册 - 负责人变动申请'), ('registration_meeting_minutes', '社团注册 - 社团大会会议记录'), ('registration_name_change', '社团注册 - 社团名称变更申请表'), ('registration_advisor_change', '社团注册 - 指导老师变动申请表'), ('registration_business_unit_change', '社团注册 - 业务指导单位变动申请表'), ('registration_social_media', '社团注册 - 新媒体平台建立申请表'), ('club_creation', '社团创建文件'), ('leader_change', '社长变更申请')], max_length=50, verbose_name='模板类型')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('file', models.FileField(upload_to='templates/%Y/%m/', verbose_name='模板文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '模板',
                'verbose_name_plural': '模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubApplicationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝'), ('partially_rejected', '部分拒绝')], max_length=20, verbose_name='审核结果')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('rejected_materials', models.JSONField(blank=True, default=list, verbose_name='被拒绝的材料')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clubs.clubregistrationrequest', verbose_name='社团申请')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '社团申请审核记录',
                'verbose_name_plural': '社团申请审核记录',
            },
        ),
        migrations.CreateModel(
            name='ClubRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_form', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团注册申请表')),
                ('basic_info_form', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='学生社团基础信息表')),
                ('membership_fee_form', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='会费表或免收会费说明书')),
                ('leader_change_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团主要负责人变动申请')),
                ('meeting_minutes', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团大会会议记录')),
                ('name_change_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团名称变更申请表')),
                ('advisor_change_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团指导老师变动申请表')),
                ('business_advisor_change_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团业务指导单位变动申请表')),
                ('new_media_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='新媒体平台建立申请表')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝'), ('partially_rejected', '部分拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='clubs.club', verbose_name='社团')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '社团注册',
                'verbose_name_plural': '社团注册',
            },
        ),
        migrations.CreateModel(
            name='ClubRegistrationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝'), ('partially_rejected', '部分拒绝')], max_length=20, verbose_name='审核结果')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('rejected_materials', models.JSONField(blank=True, default=list, verbose_name='被拒绝的材料')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clubs.clubregistration', verbose_name='社团注册')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '社团注册审核记录',
                'verbose_name_plural': '社团注册审核记录',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝'), ('partially_rejected', '部分拒绝')], max_length=20, verbose_name='审核结果')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clubs.reviewsubmission', verbose_name='年审材料')),
                ('rejected_materials', models.JSONField(blank=True, default=list, verbose_name='被拒绝的材料')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
                'ordering': ['-reviewed_at'],
                'unique_together': {('submission', 'reviewer')},
            },
        ),
        migrations.RunPython(
            code=migrate_names,
            reverse_code=reverse_migrate,
        ),
        migrations.AlterField(
            model_name='clubapplicationreview',
            name='status',
            field=models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝')], max_length=20, verbose_name='审核结果'),
        ),
        migrations.AlterField(
            model_name='clubregistration',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='clubregistrationreview',
            name='status',
            field=models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝')], max_length=20, verbose_name='审核结果'),
        ),
        migrations.AlterField(
            model_name='reviewsubmission',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='submissionreview',
            name='status',
            field=models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝')], max_length=20, verbose_name='审核结果'),
        ),
        migrations.CreateModel(
            name='RegistrationPeriod',
            fields=[
                ('period_number', models.AutoField(primary_key=True, serialize=False, verbose_name='周期编号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '社团注册周期',
                'verbose_name_plural': '社团注册周期',
                'ordering': ['-period_number'],
            },
        ),
        migrations.AddField(
            model_name='clubregistration',
            name='registration_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='clubs.registrationperiod', verbose_name='注册周期'),
        ),
        migrations.DeleteModel(
            name='LeaderChange',
        ),
        migrations.AddField(
            model_name='club',
            name='registration_enabled',
            field=models.BooleanField(default=False, verbose_name='是否开启注册'),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='社长是否已读'),
        ),
        migrations.AddField(
            model_name='clubregistration',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='社长是否已读'),
        ),
        migrations.AddField(
            model_name='clubregistrationrequest',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='社长是否已读'),
        ),
        migrations.AlterUniqueTogether(
            name='clubapplicationreview',
            unique_together={('application', 'reviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='clubregistrationreview',
            unique_together={('registration', 'reviewer')},
        ),
        migrations.RemoveField(
            model_name='reimbursement',
            name='proof_document',
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='receipt_file',
            field=models.FileField(upload_to='reimbursements/%Y/%m/', verbose_name='报销凭证'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='reimbursement_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='报销金额'),
        ),
        migrations.AddField(
            model_name='clubregistrationrequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_club_registrations', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reimbursements', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('qq', 'QQ邮箱'), ('163', '163邮箱'), ('outlook', 'Outlook'), ('gmail', 'Gmail'), ('custom', '自定义')], max_length=20, verbose_name='邮箱服务商')),
                ('smtp_host', models.CharField(max_length=100, verbose_name='SMTP服务器地址')),
                ('smtp_port', models.IntegerField(verbose_name='SMTP端口')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='发送邮箱地址')),
                ('sender_password', models.CharField(help_text='某些邮箱需要使用授权码而非密码', max_length=255, verbose_name='邮箱密码/授权码')),
                ('use_tls', models.BooleanField(default=True, verbose_name='是否使用TLS加密')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'SMTP配置',
                'verbose_name_plural': 'SMTP配置',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='待验证邮箱')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
        migrations.AddField(
            model_name='clubinfochangerequest',
            name='resubmission_attempt',
            field=models.IntegerField(default=1, verbose_name='提交次数'),
        ),
        migrations.AddField(
            model_name='clubregistrationrequest',
            name='resubmission_attempt',
            field=models.IntegerField(default=1, verbose_name='提交次数'),
        ),
        migrations.CreateModel(
            name='ActivityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200, verbose_name='活动名称')),
                ('activity_type', models.CharField(choices=[('academic', '学术类'), ('cultural', '文化类'), ('sports', '体育类'), ('volunteer', '志愿类'), ('entertainment', '娱乐类'), ('other', '其他')], default='other', max_length=20, verbose_name='活动类型')),
                ('activity_description', models.TextField(verbose_name='活动描述')),
                ('activity_date', models.DateField(verbose_name='活动日期')),
                ('activity_time_start', models.TimeField(verbose_name='活动开始时间')),
                ('activity_time_end', models.TimeField(verbose_name='活动结束时间')),
                ('activity_location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('expected_participants', models.IntegerField(verbose_name='预计参与人数')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='活动预算')),
                ('application_form', models.FileField(help_text='支持上传Word文档(.docx)或PDF文件(.pdf)', upload_to='activity_application/%Y/%m/', verbose_name='活动申请表')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('staff_approved', '干事已批准'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('is_read', models.BooleanField(default=False, verbose_name='社长是否已读')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_applications', to='clubs.club', verbose_name='社团')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activities', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('resubmission_attempt', models.IntegerField(default=1, verbose_name='提交次数')),
                ('staff_approved', models.BooleanField(blank=True, null=True, verbose_name='干事是否批准')),
                ('staff_comment', models.TextField(blank=True, verbose_name='干事审核意见')),
                ('staff_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='干事审核时间')),
                ('staff_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_reviewed_activities', to=settings.AUTH_USER_MODEL, verbose_name='干事审核人')),
            ],
            options={
                'verbose_name': '活动申请',
                'verbose_name_plural': '活动申请',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='clubregistration',
            name='resubmission_attempt',
            field=models.IntegerField(default=1, verbose_name='提交次数'),
        ),
        migrations.CreateModel(
            name='PresidentTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_date', models.DateField(verbose_name='换届日期')),
                ('transition_reason', models.TextField(verbose_name='换届原因')),
                ('transition_form', models.FileField(help_text='支持上传Word文档(.docx)或PDF文件(.pdf)', upload_to='president_transition/%Y/%m/', verbose_name='社团主要负责人变动申请表')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('is_read', models.BooleanField(default=False, verbose_name='社长是否已读')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president_transitions', to='clubs.club', verbose_name='社团')),
                ('old_president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to=settings.AUTH_USER_MODEL, verbose_name='原社长')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transitions', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('new_president_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='clubs.officer', verbose_name='新社长干部记录')),
                ('resubmission_attempt', models.IntegerField(default=1, verbose_name='提交次数')),
            ],
            options={
                'verbose_name': '社长换届申请',
                'verbose_name_plural': '社长换届申请',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='resubmission_attempt',
            field=models.IntegerField(default=1, verbose_name='提交次数'),
        ),
        migrations.AddField(
            model_name='reviewsubmission',
            name='resubmission_attempt',
            field=models.IntegerField(default=1, verbose_name='提交次数'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('president', '社长'), ('staff', '干事'), ('admin', '管理员')], default='president', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='position',
            field=models.CharField(choices=[('president', '社长')], max_length=20, verbose_name='职位'),
        ),
        migrations.CreateModel(
            name='Room222Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='借用日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('purpose', models.TextField(verbose_name='借用目的')),
                ('participant_count', models.IntegerField(verbose_name='预计使用人数')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('special_requirements', models.TextField(blank=True, help_text='如需要投影仪、音响等设备', verbose_name='特殊需求')),
                ('status', models.CharField(choices=[('active', '有效'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_bookings', to='clubs.club', verbose_name='所属社团')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to=settings.AUTH_USER_MODEL, verbose_name='借用人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '222房间借用',
                'verbose_name_plural': '222房间借用',
                'ordering': ['booking_date', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='room222_end_time_after_start_time')],
            },
        ),
    ]
