# Generated by Django 5.2.8 on 2025-11-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('review_financial', '年审 - 财务报告'), ('review_activity', '年审 - 活动报告'), ('review_member_list', '年审 - 成员名单'), ('reimbursement', '报销模板'), ('club_creation', '社团创建文件'), ('leader_change', '社长变更申请')], max_length=30, verbose_name='模板类型'),
        ),
    ]
