# Generated by Django 5.2.16 on 2026-08-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=32, unique=True, verbose_name='文件MD5')),
                ('storage_name', models.CharField(max_length=512, unique=True, verbose_name='存储路径')),
                ('ref_count', models.PositiveIntegerField(default=1, verbose_name='引用计数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文件去重记录',
                'verbose_name_plural': '文件去重记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
