# Generated by Django 5.2.8 on 2026-02-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequirement',
            name='icon',
            field=models.CharField(default='cloud_upload', help_text='Material Icons 图标名称', max_length=50, verbose_name='图标'),
        ),
        migrations.DeleteModel(
            name='ClubInfoChangeRequest',
        ),
    ]
