# Generated by Django 6.0.7 on 2026-08-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_fileblob'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileblob',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)'),
        ),
    ]
