# Generated by Django 5.2.8 on 2025-11-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_template_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='political_status',
            field=models.CharField(choices=[('communist_party_member', '中共党员'), ('communist_party_probationary', '中共预备党员'), ('communist_youth_league', '共青团员'), ('revolutionary_committee', '民革党员'), ('china_democratic_league', '民盟盟员'), ('democratic_national_construction', '民建会员'), ('china_peasants_workers_democratic', '农工党党员'), ('china_council_for_promoting', '致公党党员'), ('jiusanshe', '九三学社社员'), ('taiwan_democratic_self_government', '台盟盟员'), ('non_party_personage', '无党派人士'), ('progressive', '入党积极分子'), ('non_member', '群众')], default='non_member', max_length=40, verbose_name='政治面貌'),
        ),
    ]
