# Generated by Codex.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remove_dynamic_activity_channel(apps, schema_editor):
    FormChannel = apps.get_model('clubs', 'FormChannel')
    FormChannel.objects.filter(slug='activity-application').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_dynamic_forms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(name='ActivityRegistration'),
        migrations.CreateModel(
            name='ActivityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200, verbose_name='活动名称')),
                ('activity_type', models.CharField(choices=[('academic', '学术类'), ('cultural', '文化类'), ('sports', '体育类'), ('volunteer', '志愿类'), ('entertainment', '娱乐类'), ('other', '其他')], default='other', max_length=20, verbose_name='活动类型')),
                ('activity_description', models.TextField(verbose_name='活动描述')),
                ('activity_date', models.DateField(verbose_name='活动日期')),
                ('activity_time_start', models.TimeField(verbose_name='活动开始时间')),
                ('activity_time_end', models.TimeField(verbose_name='活动结束时间')),
                ('activity_location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('expected_participants', models.IntegerField(default=0, verbose_name='预计参与人数')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='活动预算')),
                ('application_form', models.FileField(blank=True, null=True, upload_to='activity_application/%Y/%m/', verbose_name='活动申请材料')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开报名')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_applications', to='clubs.club', verbose_name='社团')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activity_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_activity_applications', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
            ],
            options={
                'verbose_name': '活动申请',
                'verbose_name_plural': '活动申请',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='clubs.activityapplication', verbose_name='活动')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_registrations', to='clubs.userprofile', verbose_name='报名用户')),
            ],
            options={
                'verbose_name': '活动报名',
                'verbose_name_plural': '活动报名',
                'unique_together': {('activity', 'user_profile')},
            },
        ),
        migrations.AlterField(
            model_name='formchannel',
            name='builtin_action',
            field=models.CharField(choices=[('none', '无'), ('annual_review', '社团年审'), ('club_registration', '社团注册'), ('club_application', '社团申请'), ('reimbursement', '报销申请'), ('president_transition', '社长换届')], default='none', max_length=50, verbose_name='内置动作'),
        ),
        migrations.RunPython(remove_dynamic_activity_channel, migrations.RunPython.noop),
    ]
