# Generated by Django 5.2.16 on 2026-08-07 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_fileblob_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='连续错误次数'),
        ),
        migrations.AlterField(
            model_name='formsubmissionreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submission_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
    ]
