# Generated by Django 5.2.8 on 2025-12-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_carouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('office', '办公室'), ('review', '评审部'), ('activity', '活动部'), ('organization', '组织部'), ('propaganda', '宣传部')], max_length=20, null=True, verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff_level',
            field=models.CharField(choices=[('member', '部员'), ('director', '部长')], default='member', help_text='仅对干事有效', max_length=20, verbose_name='部员/部长'),
        ),
    ]
