# Generated by Django 5.2.8 on 2025-11-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_userprofile_political_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewsubmission',
            name='activity_report',
        ),
        migrations.RemoveField(
            model_name='reviewsubmission',
            name='member_list',
        ),
        migrations.AddField(
            model_name='reviewsubmission',
            name='advisor_performance_report',
            field=models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='指导教师履职情况表'),
        ),
        migrations.AddField(
            model_name='reviewsubmission',
            name='annual_activity_list',
            field=models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='社团年度活动清单'),
        ),
        migrations.AddField(
            model_name='reviewsubmission',
            name='club_constitution',
            field=models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='社团章程'),
        ),
        migrations.AddField(
            model_name='reviewsubmission',
            name='leader_learning_work_report',
            field=models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='负责人学习及工作情况表'),
        ),
        migrations.AddField(
            model_name='reviewsubmission',
            name='member_composition_list',
            field=models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='社团成员构成表'),
        ),
        migrations.AddField(
            model_name='reviewsubmission',
            name='new_media_account_report',
            field=models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='新媒体账号及运维情况表'),
        ),
        migrations.AddField(
            model_name='reviewsubmission',
            name='other_materials',
            field=models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='其他材料'),
        ),
        migrations.AddField(
            model_name='reviewsubmission',
            name='self_assessment_form',
            field=models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='自查表'),
        ),
        migrations.AlterField(
            model_name='reviewsubmission',
            name='financial_report',
            field=models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='年度财务情况表'),
        ),
    ]
