# Generated by Django 5.2.16 on 2026-08-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_emailverificationcode_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileblob',
            name='storage_name',
            field=models.CharField(max_length=191, unique=True, verbose_name='存储路径'),
        ),
    ]
