# Generated by Django 5.2.8 on 2025-12-27 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_userprofile_department_userprofile_staff_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('office', '办公室'), ('review', '评审部'), ('activity', '活动部'), ('organization', '组织部'), ('propaganda', '宣传部')], max_length=20, unique=True, verbose_name='部门')),
                ('description', models.TextField(verbose_name='职责描述')),
                ('highlights', models.TextField(blank=True, help_text='多个重点工作用换行分隔', verbose_name='重点工作')),
                ('icon', models.CharField(default='work', help_text='Material Icons图标名称', max_length=50, verbose_name='图标名称')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '部门介绍',
                'verbose_name_plural': '部门介绍',
                'ordering': ['department'],
            },
        ),
    ]
