# Generated by Django 5.2.8 on 2025-11-27 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_remove_reviewsubmission_activity_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubregistrationrequest',
            name='registration_materials',
            field=models.FileField(blank=True, help_text='支持上传压缩包(.zip, .rar)和Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='注册材料'),
        ),
        migrations.AlterField(
            model_name='clubregistrationrequest',
            name='members_count',
            field=models.IntegerField(verbose_name='成员数'),
        ),
        migrations.CreateModel(
            name='StaffClubRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_staff', to='clubs.club', verbose_name='社团')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_clubs', to='clubs.userprofile', verbose_name='干事')),
            ],
            options={
                'verbose_name': '干事负责社团',
                'verbose_name_plural': '干事负责社团',
                'unique_together': {('staff', 'club')},
            },
        ),
    ]
