# Generated by Django 5.2.12 on 2026-06-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_dynamic_business_forms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='registration_enabled',
        ),
        migrations.RemoveField(
            model_name='club',
            name='review_enabled',
        ),
    ]
