# Generated by Django 5.2.12 on 2026-06-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_remove_club_registration_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedactivity',
            name='activity_type',
            field=models.CharField(choices=[('讲座', '讲座'), ('比赛', '比赛'), ('演出', '演出'), ('培训', '培训'), ('志愿服务', '志愿服务'), ('其他', '其他')], default='其他', max_length=40, verbose_name='活动类型'),
        ),
    ]
