# Generated by Django 5.2.7 on 2025-11-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_clubregistrationrequest_registration_materials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='announcements/%Y/%m/', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('review_financial', '年审 - 财务报告'), ('review_activity', '年审 - 活动报告'), ('review_member_list', '年审 - 成员名单'), ('review_self_assessment', '年审 - 自查表'), ('review_club_constitution', '年审 - 社团章程'), ('review_leader_report', '年审 - 负责人学习及工作情况表'), ('review_annual_activity', '年审 - 社团年度活动清单'), ('review_advisor_report', '年审 - 指导教师履职情况表'), ('review_member_composition', '年审 - 社团成员构成表'), ('review_media_account', '年审 - 新媒体账号及运维情况表'), ('reimbursement', '报销模板'), ('club_creation', '社团创建文件'), ('leader_change', '社长变更申请')], max_length=30, verbose_name='模板类型'),
        ),
    ]
