# Generated by Django 5.2.16 on 2026-08-07 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_fileblob_storage_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpconfig',
            name='enable_error_help',
            field=models.BooleanField(default=False, help_text='开启后，404/500 错误页将显示“请求帮助”按钮', verbose_name='开启错误页求助按钮'),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='help_recipient_email',
            field=models.EmailField(blank=True, default='', help_text='用户点击求助时通知此邮箱；留空则通知所有管理员账号邮箱', max_length=254, verbose_name='求助通知收件邮箱'),
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveSmallIntegerField(choices=[(500, '500 服务器错误'), (404, '404 页面不存在')], default=500, verbose_name='状态码')),
                ('path', models.CharField(blank=True, default='', max_length=500, verbose_name='请求地址')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='请求方法')),
                ('referer', models.CharField(blank=True, default='', max_length=500, verbose_name='来源页面')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='浏览器UA')),
                ('ip', models.CharField(blank=True, default='', max_length=100, verbose_name='客户端IP')),
                ('exception_name', models.CharField(blank=True, default='', max_length=200, verbose_name='异常类型')),
                ('exception_message', models.TextField(blank=True, default='', verbose_name='异常信息')),
                ('user_identifier', models.CharField(blank=True, default='', max_length=200, verbose_name='用户标识')),
                ('help_requested', models.BooleanField(default=False, verbose_name='用户请求帮助')),
                ('help_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='求助时间')),
                ('help_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='求助联系邮箱')),
                ('help_note', models.TextField(blank=True, default='', verbose_name='用户补充说明')),
                ('resolved', models.BooleanField(default=False, verbose_name='已处理')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_error_logs', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '错误日志',
                'verbose_name_plural': '错误日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='errlog_created_idx'), models.Index(fields=['help_requested', 'resolved'], name='errlog_help_state_idx')],
            },
        ),
    ]
