# Generated by Django 5.2.16

from django.db import migrations, models


def forward_copy_switch(apps, schema_editor):
    """把旧 SMTPConfig.enable_error_help 迁移为站点级开关。"""
    SiteSettings = apps.get_model('clubs', 'SiteSettings')
    SMTPConfig = apps.get_model('clubs', 'SMTPConfig')
    settings, _ = SiteSettings.objects.get_or_create(pk=1)
    active = SMTPConfig.objects.filter(is_active=True).order_by('-pk').first()
    if active is not None and active.enable_error_help:
        settings.error_help_enabled = True
        settings.save(update_fields=['error_help_enabled'])


def backward_copy_switch(apps, schema_editor):
    """反向迁移：把站点级开关写回现有 SMTP 配置。"""
    SiteSettings = apps.get_model('clubs', 'SiteSettings')
    SMTPConfig = apps.get_model('clubs', 'SMTPConfig')
    try:
        settings = SiteSettings.objects.get(pk=1)
    except SiteSettings.DoesNotExist:
        return
    SMTPConfig.objects.all().update(enable_error_help=settings.error_help_enabled)


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_errorlog_and_smtp_error_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtpconfig',
            name='help_recipient_email',
            field=models.EmailField(
                blank=True,
                default='',
                help_text='配置 SMTP 后，用户点击求助时通知此邮箱；留空则通知所有管理员账号邮箱',
                max_length=254,
                verbose_name='求助通知收件邮箱',
            ),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='error_help_enabled',
            field=models.BooleanField(
                default=False,
                help_text='开启后，404/500 错误页将显示“请求帮助”按钮，不依赖 SMTP 配置',
                verbose_name='开启错误页求助按钮',
            ),
        ),
        migrations.RunPython(forward_copy_switch, backward_copy_switch),
        migrations.RemoveField(
            model_name='smtpconfig',
            name='enable_error_help',
        ),
    ]
