# Generated by Django 5.2.7 on 2025-11-27 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_announcement_attachment_alter_template_template_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewsubmission',
            name='reviewer_comment',
        ),
        migrations.AddField(
            model_name='reviewsubmission',
            name='is_read_by_president',
            field=models.BooleanField(default=False, verbose_name='社长是否已读'),
        ),
        migrations.AddField(
            model_name='reviewsubmission',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='审核次数'),
        ),
        migrations.AlterField(
            model_name='reviewsubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后审核时间'),
        ),
        migrations.CreateModel(
            name='SubmissionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝')], max_length=20, verbose_name='审核结果')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clubs.reviewsubmission', verbose_name='年审材料')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
                'ordering': ['-reviewed_at'],
                'unique_together': {('submission', 'reviewer')},
            },
        ),
    ]
