# Generated by Django 5.2.7 on 2025-11-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_remove_reviewsubmission_reviewer_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionreview',
            name='rejected_materials',
            field=models.JSONField(blank=True, default=list, verbose_name='被拒绝的材料'),
        ),
    ]
