# Generated by Django 5.2.16 on 2026-08-07

from django.db import migrations


def drop_stale_removed_columns(apps, schema_editor):
    """清理旧版遗留、当前模型已移除的列（幂等，仅 MySQL 执行）。

    历史生产库可能通过 --fake 应用过压缩迁移，旧列并未真正删除；
    MySQL 严格模式下 NOT NULL 且无默认值的旧列（如 source_name）
    会让正常 INSERT 直接报 1364 错误。
    """
    from django.db import connection

    if connection.vendor != 'mysql':
        return

    stale_columns = [
        ('clubs_club', 'registration_enabled'),
        ('clubs_club', 'review_enabled'),
        ('clubs_formuploadedfile', 'source_name'),
        ('clubs_registrationtoken', 'is_used'),
        ('clubs_storageconfig', 's3_use_path_style'),
        ('clubs_userprofile', 'department'),
    ]
    with connection.cursor() as cursor:
        for table, column in stale_columns:
            cursor.execute(
                'SELECT COUNT(*) FROM information_schema.COLUMNS '
                'WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s AND COLUMN_NAME = %s',
                [table, column],
            )
            if cursor.fetchone()[0]:
                cursor.execute(f'ALTER TABLE `{table}` DROP COLUMN `{column}`')


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_error_help_site_setting'),
    ]

    operations = [
        migrations.RunPython(drop_stale_removed_columns, migrations.RunPython.noop),
    ]
