# Generated by Django 5.2.16 on 2026-08-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_cleanup_stale_removed_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelexamplefile',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='显示文件名'),
        ),
    ]
