# Generated by Django 5.2.7 on 2025-11-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_submissionreview_rejected_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_info_public',
            field=models.BooleanField(default=False, verbose_name='是否公开个人信息'),
        ),
    ]
