# Generated by Django 5.2.7 on 2025-11-28 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_userprofile_is_info_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubregistrationrequest',
            name='registration_materials',
        ),
        migrations.AddField(
            model_name='clubregistrationrequest',
            name='advisor_certificates',
            field=models.FileField(blank=True, help_text='支持上传压缩包(.zip, .rar)或图片文件(.jpg, .png)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团老师的相关专业证书'),
        ),
        migrations.AddField(
            model_name='clubregistrationrequest',
            name='constitution_draft',
            field=models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团章程草案'),
        ),
        migrations.AddField(
            model_name='clubregistrationrequest',
            name='establishment_application',
            field=models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团成立申请书'),
        ),
        migrations.AddField(
            model_name='clubregistrationrequest',
            name='leaders_resumes',
            field=models.FileField(blank=True, help_text='支持上传压缩包(.zip, .rar)或Word文档(.docx)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团拟任负责人和指导老师的详细简历和身份证复印件'),
        ),
        migrations.AddField(
            model_name='clubregistrationrequest',
            name='one_month_activity_plan',
            field=models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团组建一个月后的活动计划'),
        ),
        migrations.AddField(
            model_name='clubregistrationrequest',
            name='three_year_plan',
            field=models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_application/%Y/%m/', verbose_name='社团三年发展规划'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('review_financial', '年审 - 财务报告'), ('review_activity', '年审 - 活动报告'), ('review_member_list', '年审 - 成员名单'), ('review_self_assessment', '年审 - 自查表'), ('review_club_constitution', '年审 - 社团章程'), ('review_leader_report', '年审 - 负责人学习及工作情况表'), ('review_annual_activity', '年审 - 社团年度活动清单'), ('review_advisor_report', '年审 - 指导教师履职情况表'), ('review_member_composition', '年审 - 社团成员构成表'), ('review_media_account', '年审 - 新媒体账号及运维情况表'), ('reimbursement', '报销模板'), ('application_establishment', '社团申请 - 社团成立申请书'), ('application_constitution', '社团申请 - 社团章程草案'), ('application_three_year_plan', '社团申请 - 社团三年发展规划'), ('application_leader_resume', '社团申请 - 负责人简历'), ('application_advisor_resume', '社团申请 - 指导老师简历'), ('application_id_copies', '社团申请 - 身份证复印件'), ('application_monthly_plan', '社团申请 - 一个月活动计划'), ('application_teacher_certificates', '社团申请 - 指导老师专业证书'), ('registration_form', '社团注册 - 社团注册申请表'), ('registration_basic_info', '社团注册 - 学生社团基础信息表'), ('registration_fee_form', '社团注册 - 会费表'), ('registration_fee_exemption', '社团注册 - 免收会费说明书'), ('registration_leader_change', '社团注册 - 负责人变动申请'), ('registration_meeting_minutes', '社团注册 - 社团大会会议记录'), ('registration_name_change', '社团注册 - 社团名称变更申请表'), ('registration_advisor_change', '社团注册 - 指导老师变动申请表'), ('registration_business_unit_change', '社团注册 - 业务指导单位变动申请表'), ('registration_social_media', '社团注册 - 新媒体平台建立申请表'), ('club_creation', '社团创建文件'), ('leader_change', '社长变更申请')], max_length=50, verbose_name='模板类型'),
        ),
        migrations.CreateModel(
            name='ClubApplicationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝'), ('partially_rejected', '部分拒绝')], max_length=20, verbose_name='审核结果')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('rejected_materials', models.JSONField(blank=True, default=list, verbose_name='被拒绝的材料')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clubs.clubregistrationrequest', verbose_name='社团申请')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '社团申请审核记录',
                'verbose_name_plural': '社团申请审核记录',
            },
        ),
        migrations.CreateModel(
            name='ClubRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_form', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团注册申请表')),
                ('basic_info_form', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='学生社团基础信息表')),
                ('membership_fee_form', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='会费表或免收会费说明书')),
                ('leader_change_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团主要负责人变动申请')),
                ('meeting_minutes', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团大会会议记录')),
                ('name_change_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团名称变更申请表')),
                ('advisor_change_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团指导老师变动申请表')),
                ('business_advisor_change_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='社团业务指导单位变动申请表')),
                ('new_media_application', models.FileField(blank=True, help_text='支持上传Word文档(.docx)', null=True, upload_to='club_registration/%Y/%m/', verbose_name='新媒体平台建立申请表')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='clubs.club', verbose_name='社团')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请用户')),
            ],
            options={
                'verbose_name': '社团注册',
                'verbose_name_plural': '社团注册',
            },
        ),
        migrations.CreateModel(
            name='ClubRegistrationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝')], max_length=20, verbose_name='审核结果')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
                ('rejected_materials', models.JSONField(blank=True, default=list, verbose_name='被拒绝的材料')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clubs.clubregistration', verbose_name='社团注册')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_reviews', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '社团注册审核记录',
                'verbose_name_plural': '社团注册审核记录',
            },
        ),
    ]
