# Generated by Django 5.2.16 on 2026-08-08 19:11

import clubs.crypto_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_channelexamplefile_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='auto_translate_enabled',
            field=models.BooleanField(default=False, help_text='开启后，通道与字段设置页可一键调用翻译服务生成英文、维吾尔语和蒙古语文案；关闭时仅保留手动填写。', verbose_name='开启内容自动翻译'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='translation_api_base_url',
            field=models.CharField(default='https://uapis.cn', help_text='默认使用 UAPI 公共翻译服务 https://uapis.cn；自建或兼容网关请填完整地址。', max_length=500, verbose_name='翻译服务地址'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='translation_api_key',
            field=clubs.crypto_fields.EncryptedCharField(blank=True, default='', help_text='UAPI 控制台可免费申请；公共接口匿名调用也可用，留空即可。', max_length=500, verbose_name='翻译服务 API Key'),
        ),
        migrations.CreateModel(
            name='ObjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('formchannel', 'FormChannel'), ('formfield', 'FormField'), ('formcycle', 'FormCycle'), ('channelexamplefile', 'ChannelExampleFile')], max_length=20, verbose_name='对象类型')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='对象ID')),
                ('field_name', models.CharField(max_length=30, verbose_name='字段名')),
                ('language', models.CharField(max_length=10, verbose_name='语言代码')),
                ('text', models.TextField(verbose_name='译文')),
                ('auto_translated', models.BooleanField(default=False, help_text='由 UAPI 翻译服务自动生成，可手动覆盖', verbose_name='是否机器翻译')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '对象翻译',
                'verbose_name_plural': '对象翻译',
                'ordering': ['object_type', 'object_id', 'field_name', 'language'],
                'constraints': [models.UniqueConstraint(fields=('object_type', 'object_id', 'field_name', 'language'), name='unique_obj_translation')],
            },
        ),
    ]
