# Generated by Django 5.2.7 on 2025-11-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_remove_clubregistrationrequest_registration_materials_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubregistrationreview',
            options={'ordering': ['-reviewed_at'], 'verbose_name': '社团注册审核记录', 'verbose_name_plural': '社团注册审核记录'},
        ),
        migrations.AlterField(
            model_name='clubregistrationreview',
            name='status',
            field=models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝'), ('partially_rejected', '部分拒绝')], max_length=20, verbose_name='审核结果'),
        ),
        migrations.AlterField(
            model_name='reviewsubmission',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝'), ('partially_rejected', '部分拒绝')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='submissionreview',
            name='status',
            field=models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝'), ('partially_rejected', '部分拒绝')], max_length=20, verbose_name='审核结果'),
        ),
    ]
