# Generated by Django 5.2.16 on 2026-08-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_sitesettings_auto_translate_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_language',
            field=models.CharField(choices=[('zh-hans', '简体中文'), ('en', 'English'), ('ug', 'ئۇيغۇرچە'), ('mn', 'Монгол')], default='zh-hans', help_text='未登录用户与未设置首选语言的用户将使用此语言；默认简体中文。', max_length=10, verbose_name='全站默认语言'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('', '跟随站点默认语言'), ('zh-hans', '简体中文'), ('en', 'English'), ('ug', 'ئۇيغۇرچە'), ('mn', 'Монгол')], default='', help_text='留空则跟随站点默认语言；选择后会跨设备同步保留。', max_length=10, verbose_name='首选语言'),
        ),
    ]
