# Generated by Django 5.2.7 on 2025-11-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_alter_clubregistrationreview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubregistration',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝'), ('partially_rejected', '部分拒绝')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
