# Generated by Django 5.2.8 on 2025-12-04 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_consolidate_name_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubapplicationreview',
            name='status',
            field=models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝')], max_length=20, verbose_name='审核结果'),
        ),
        migrations.AlterField(
            model_name='clubregistration',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='clubregistrationreview',
            name='status',
            field=models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝')], max_length=20, verbose_name='审核结果'),
        ),
        migrations.AlterField(
            model_name='reviewsubmission',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='submissionreview',
            name='status',
            field=models.CharField(choices=[('approved', '已批准'), ('rejected', '被拒绝')], max_length=20, verbose_name='审核结果'),
        ),
        migrations.CreateModel(
            name='RegistrationPeriod',
            fields=[
                ('period_number', models.AutoField(primary_key=True, serialize=False, verbose_name='周期编号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '社团注册周期',
                'verbose_name_plural': '社团注册周期',
                'ordering': ['-period_number'],
            },
        ),
        migrations.AddField(
            model_name='clubregistration',
            name='registration_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='clubs.registrationperiod', verbose_name='注册周期'),
        ),
        migrations.DeleteModel(
            name='LeaderChange',
        ),
    ]
