# Generated by Django 6.0.6 on 2026-06-30 14:24

from django.db import migrations, models


def migration_init_default_storage(apps, schema_editor):
    """初始化默认本地存储配置（单例 pk=1）。"""
    StorageConfig = apps.get_model("clubs", "StorageConfig")
    if not StorageConfig.objects.filter(pk=1).exists():
        StorageConfig.objects.create(
            pk=1,
            backend_type='local',
            is_active=True,
        )


def migration_remove_default_storage(apps, schema_editor):
    """回滚：删除默认配置。"""
    StorageConfig = apps.get_model("clubs", "StorageConfig")
    StorageConfig.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_squashed_0013_formchannel_show_zip_download"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backend_type",
                    models.CharField(
                        choices=[
                            ("local", "本地存储"),
                            (
                                "s3",
                                "S3 兼容对象存储（AWS S3 / MinIO / 阿里云 OSS / 腾讯云 COS 等）",
                            ),
                        ],
                        default="local",
                        help_text="选择文件存储位置。切换后立即生效，已存文件不会自动迁移。",
                        max_length=20,
                        verbose_name="后端类型",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="关闭后强制降级到本地存储（紧急回退用）",
                        verbose_name="是否启用",
                    ),
                ),
                (
                    "s3_endpoint_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AWS S3 留空；MinIO/阿里云/腾讯云等填兼容端点，如 https://s3.cn-north-1.amazonaws.com.cn",
                        max_length=500,
                        verbose_name="S3 Endpoint URL",
                    ),
                ),
                (
                    "s3_region",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="AWS S3 必填，如 us-east-1；MinIO 可留空",
                        max_length=100,
                        verbose_name="Region",
                    ),
                ),
                (
                    "s3_bucket_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="需提前在 S3 控制台创建；Office Online 预览要求 bucket 可公网匿名访问",
                        max_length=255,
                        verbose_name="Bucket 名称",
                    ),
                ),
                (
                    "s3_access_key_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="AccessKey ID",
                    ),
                ),
                (
                    "s3_secret_access_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="明文存储，请确保数据库访问严格受控",
                        max_length=500,
                        verbose_name="Secret Access Key",
                    ),
                ),
                (
                    "s3_custom_domain",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="如已配置 CDN，填写 CDN 域名（如 https://cdn.example.com）。留空则使用 S3 默认 URL。",
                        max_length=500,
                        verbose_name="自定义域名 / CDN",
                    ),
                ),
                (
                    "s3_addressing_style",
                    models.CharField(
                        choices=[
                            ("auto", "自动（推荐）"),
                            ("path", "Path Style（适用于 MinIO / 自建）"),
                            ("virtual", "Virtual Hosted Style（适用于 AWS S3）"),
                        ],
                        default="auto",
                        help_text="MinIO / 自建 S3 通常选 Path Style；AWS S3 选 Virtual Hosted",
                        max_length=20,
                        verbose_name="地址风格",
                    ),
                ),
                (
                    "s3_use_path_style",
                    models.BooleanField(
                        default=True,
                        help_text="与 address_style 互补，兼容部分 MinIO 版本",
                        verbose_name="强制 Path Style",
                    ),
                ),
                (
                    "presigned_url_expiration",
                    models.IntegerField(
                        default=3600,
                        help_text="私密 bucket 下载链接的有效时长，默认 1 小时",
                        verbose_name="预签名 URL 有效期（秒）",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "存储配置",
                "verbose_name_plural": "存储配置",
            },
        ),
        migrations.RunPython(
            migration_init_default_storage,
            migration_remove_default_storage,
        ),
    ]
