# Generated by Django 6.0.7 on 2026-07-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_storageconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='link_url',
            field=models.CharField(blank=True, help_text='可填写站内路径（如 /clubs/）或 http(s) 完整地址', max_length=500, verbose_name='跳转链接'),
        ),
    ]
