# Generated by Django 5.2.8 on 2025-12-05 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_alter_clubapplicationreview_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200, verbose_name='活动名称')),
                ('activity_type', models.CharField(choices=[('academic', '学术类'), ('cultural', '文化类'), ('sports', '体育类'), ('volunteer', '志愿类'), ('entertainment', '娱乐类'), ('other', '其他')], default='other', max_length=20, verbose_name='活动类型')),
                ('activity_description', models.TextField(verbose_name='活动描述')),
                ('activity_date', models.DateField(verbose_name='活动日期')),
                ('activity_time_start', models.TimeField(verbose_name='活动开始时间')),
                ('activity_time_end', models.TimeField(verbose_name='活动结束时间')),
                ('activity_location', models.CharField(max_length=200, verbose_name='活动地点')),
                ('expected_participants', models.IntegerField(verbose_name='预计参与人数')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='活动预算')),
                ('application_form', models.FileField(help_text='支持上传Word文档(.docx)或PDF文件(.pdf)', upload_to='activity_application/%Y/%m/', verbose_name='活动申请表')),
                ('activity_plan', models.FileField(blank=True, help_text='支持上传Word文档(.docx)或PDF文件(.pdf)', null=True, upload_to='activity_application/%Y/%m/', verbose_name='活动方案')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('is_read', models.BooleanField(default=False, verbose_name='社长是否已读')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_applications', to='clubs.club', verbose_name='社团')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activities', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '活动申请',
                'verbose_name_plural': '活动申请',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PresidentTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_president_name', models.CharField(max_length=100, verbose_name='新社长姓名')),
                ('new_president_student_id', models.CharField(max_length=50, verbose_name='新社长学号')),
                ('new_president_phone', models.CharField(max_length=20, verbose_name='新社长电话')),
                ('new_president_email', models.EmailField(blank=True, max_length=254, verbose_name='新社长邮箱')),
                ('transition_date', models.DateField(verbose_name='换届日期')),
                ('transition_reason', models.TextField(verbose_name='换届原因')),
                ('transition_form', models.FileField(help_text='支持上传Word文档(.docx)或PDF文件(.pdf)', upload_to='president_transition/%Y/%m/', verbose_name='社团主要负责人变动申请表')),
                ('meeting_minutes', models.FileField(blank=True, help_text='支持上传Word文档(.docx)或PDF文件(.pdf)', null=True, upload_to='president_transition/%Y/%m/', verbose_name='社团大会会议记录')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('is_read', models.BooleanField(default=False, verbose_name='社长是否已读')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president_transitions', to='clubs.club', verbose_name='社团')),
                ('old_president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to=settings.AUTH_USER_MODEL, verbose_name='原社长')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transitions', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '社长换届申请',
                'verbose_name_plural': '社长换届申请',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Room222Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='借用日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('purpose', models.TextField(verbose_name='借用目的')),
                ('participant_count', models.IntegerField(verbose_name='预计使用人数')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('special_requirements', models.TextField(blank=True, help_text='如需要投影仪、音响等设备', verbose_name='特殊需求')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '被拒绝'), ('cancelled', '已取消'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_bookings', to='clubs.club', verbose_name='所属社团')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_room_bookings', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to=settings.AUTH_USER_MODEL, verbose_name='借用人')),
            ],
            options={
                'verbose_name': '222房间借用',
                'verbose_name_plural': '222房间借用',
                'ordering': ['booking_date', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='room222_end_time_after_start_time')],
            },
        ),
    ]
