# Generated by Codex on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_announcement_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='formchannel',
            name='publish_status',
            field=models.CharField(
                choices=[('draft', '草稿'), ('published', '已发布')],
                default='published',
                max_length=20,
                verbose_name='发布状态',
            ),
        ),
        migrations.AlterField(
            model_name='formchannel',
            name='publish_status',
            field=models.CharField(
                choices=[('draft', '草稿'), ('published', '已发布')],
                default='draft',
                max_length=20,
                verbose_name='发布状态',
            ),
        ),
    ]
