# Generated by Django 5.2.8 on 2025-12-05 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_activityapplication_presidenttransition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room222booking',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='room222booking',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='room222booking',
            name='reviewer_comment',
        ),
        migrations.RemoveField(
            model_name='room222booking',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='room222booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room222booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='room222booking',
            name='status',
            field=models.CharField(choices=[('active', '有效'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态'),
        ),
    ]
