# Generated by Django 5.2.8 on 2025-12-05 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_remove_room222booking_reviewed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presidenttransition',
            name='new_president_email',
        ),
        migrations.RemoveField(
            model_name='presidenttransition',
            name='new_president_name',
        ),
        migrations.RemoveField(
            model_name='presidenttransition',
            name='new_president_phone',
        ),
        migrations.RemoveField(
            model_name='presidenttransition',
            name='new_president_student_id',
        ),
        migrations.AddField(
            model_name='presidenttransition',
            name='new_president_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='clubs.officer', verbose_name='新社长干部记录'),
        ),
    ]
