# Generated by Django 6.0.7 on 2026-07-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_formchannel_publish_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formchannel',
            name='cycle_type',
            field=models.CharField(choices=[('none', '无周期'), ('count', '按轮次'), ('year', '按年份'), ('month', '按月份'), ('day', '按日期')], default='none', max_length=20, verbose_name='周期判断方式'),
        ),
    ]
