# Generated by Django 5.2.8 on 2025-12-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_remove_presidenttransition_new_president_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityapplication',
            name='activity_plan',
        ),
        migrations.RemoveField(
            model_name='presidenttransition',
            name='meeting_minutes',
        ),
    ]
