# Generated by Django 5.2.8 on 2025-12-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_remove_activityapplication_activity_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='registration_enabled',
            field=models.BooleanField(default=False, verbose_name='是否开启注册'),
        ),
    ]
