# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_add_registration_enabled_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='社长是否已读'),
        ),
        migrations.AddField(
            model_name='clubregistration',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='社长是否已读'),
        ),
        migrations.AddField(
            model_name='clubregistrationrequest',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='社长是否已读'),
        ),
    ]
