# Generated by Django 5.2.8 on 2025-12-07 07:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_add_is_read_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubapplicationreview',
            unique_together={('application', 'reviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='clubregistrationreview',
            unique_together={('registration', 'reviewer')},
        ),
    ]
