# Generated by Django 5.2.8 on 2025-12-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_add_unique_constraints_for_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reimbursement',
            name='proof_document',
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='receipt_file',
            field=models.FileField(upload_to='reimbursements/%Y/%m/', verbose_name='报销凭证'),
        ),
    ]
