# Generated by Django 5.2.8 on 2025-12-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0022_remove_proof_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='reimbursement_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='报销金额'),
        ),
    ]
