# Generated by Django 6.0.7 on 2026-08-03 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0022_config_change_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityregistration',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='clubmember',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='formchannelclubstate',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='formcycle',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='formfield',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='formfieldvalue',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='formsubmissionreview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='officer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='staffclubrelation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='activityregistration',
            constraint=models.UniqueConstraint(fields=('activity', 'user_profile'), name='unique_activity_user'),
        ),
        migrations.AddConstraint(
            model_name='clubmember',
            constraint=models.UniqueConstraint(fields=('club', 'user_profile'), name='unique_club_member'),
        ),
        migrations.AddConstraint(
            model_name='formchannelclubstate',
            constraint=models.UniqueConstraint(fields=('channel', 'club'), name='unique_channel_club_state'),
        ),
        migrations.AddConstraint(
            model_name='formcycle',
            constraint=models.UniqueConstraint(fields=('channel', 'sequence'), name='unique_channel_cycle_seq'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('channel', 'field_key'), name='unique_channel_field_key'),
        ),
        migrations.AddConstraint(
            model_name='formfieldvalue',
            constraint=models.UniqueConstraint(fields=('submission', 'field'), name='unique_submission_field'),
        ),
        migrations.AddConstraint(
            model_name='formsubmissionreview',
            constraint=models.UniqueConstraint(fields=('submission', 'reviewer', 'submission_attempt'), name='unique_submission_review'),
        ),
        migrations.AddConstraint(
            model_name='officer',
            constraint=models.UniqueConstraint(fields=('club', 'user_profile', 'position'), name='unique_club_officer_role'),
        ),
        migrations.AddConstraint(
            model_name='staffclubrelation',
            constraint=models.UniqueConstraint(fields=('staff', 'club'), name='unique_staff_club'),
        ),
    ]
