# Generated by Django 5.2.8 on 2025-12-08 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0023_alter_reimbursement_reimbursement_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clubregistrationrequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_club_registrations', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
    ]
