# Generated by Django 5.2.4 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0024_formsubmission_dashboard_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='third_party_cdn_base_url',
            field=models.CharField(
                default='https://cdn.bootcdn.net',
                help_text='用于加载 Chart.js、Swiper 和 Cropper.js 等 cdnjs 资源。',
                max_length=500,
                verbose_name='第三方资源 CDN 基础地址',
            ),
        ),
    ]
