# Generated by Django 5.2.8 on 2025-12-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0025_reimbursement_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('president', '社长'), ('staff', '干事'), ('admin', '管理员'), ('teacher', '老师'), ('user', '普通用户')], default='president', max_length=20, verbose_name='角色'),
        ),
    ]
