# Generated by Django 5.2.4 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0025_sitesettings_third_party_cdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='third_party_cdn_sri',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='由管理页面在切换 CDN 时自动计算。',
                verbose_name='第三方资源 SRI 校验值',
            ),
        ),
    ]
