# Generated by Django 5.2.4 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_sitesettings_third_party_cdn_sri'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_title',
            field=models.CharField(
                default='社团管理服务中心',
                help_text='显示在首页顶部横幅中的大标题',
                max_length=120,
                verbose_name='首页主标题',
            ),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(
                default='社团管理系统',
                help_text='显示在浏览器标签页标题中，修改后刷新页面生效',
                max_length=120,
                verbose_name='站点名称（浏览器标题）',
            ),
        ),
    ]
