# Generated by Django 5.2.8 on 2025-12-09 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('qq', 'QQ邮箱'), ('163', '163邮箱'), ('outlook', 'Outlook'), ('gmail', 'Gmail'), ('custom', '自定义')], max_length=20, verbose_name='邮箱服务商')),
                ('smtp_host', models.CharField(max_length=100, verbose_name='SMTP服务器地址')),
                ('smtp_port', models.IntegerField(verbose_name='SMTP端口')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='发送邮箱地址')),
                ('sender_password', models.CharField(help_text='某些邮箱需要使用授权码而非密码', max_length=255, verbose_name='邮箱密码/授权码')),
                ('use_tls', models.BooleanField(default=True, verbose_name='是否使用TLS加密')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'SMTP配置',
                'verbose_name_plural': 'SMTP配置',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='待验证邮箱')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
    ]
