# Generated by Django 5.2.4 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0027_sitesettings_site_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='homepage_subtitle',
            field=models.CharField(
                default='致力于为社团提供全方位的管理与服务支持，促进社团健康发展',
                help_text='显示在首页顶部横幅中主标题下方',
                max_length=300,
                verbose_name='首页副标题',
            ),
        ),
    ]
