# Generated by Django 5.2.8 on 2025-12-09 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0027_smtpconfig_emailverificationcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherClubAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('advisor', '指导老师'), ('supervisor', '监管员'), ('reviewer', '审核员')], default='advisor', max_length=20, verbose_name='角色')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='分配日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to='clubs.club', verbose_name='社团')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_club_assignments', to=settings.AUTH_USER_MODEL, verbose_name='教师用户')),
            ],
            options={
                'verbose_name': '教师社团分配',
                'verbose_name_plural': '教师社团分配',
                'ordering': ['-assigned_date'],
                'unique_together': {('user', 'club')},
            },
        ),
    ]
