# Generated by Django 5.2.4 on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0028_sitesettings_homepage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='formchannel',
            name='example_file',
            field=models.FileField(
                blank=True,
                help_text='显示在提交页顶部的可选示例文件',
                null=True,
                upload_to='channel_examples/%Y/%m/',
                verbose_name='通道示例文件',
            ),
        ),
    ]
