# Generated by Django 5.2.8 on 2025-12-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0028_teacherclubassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityapplication',
            name='resubmission_attempt',
            field=models.IntegerField(default=1, verbose_name='提交次数'),
        ),
        migrations.AddField(
            model_name='clubinfochangerequest',
            name='resubmission_attempt',
            field=models.IntegerField(default=1, verbose_name='提交次数'),
        ),
        migrations.AddField(
            model_name='clubregistrationrequest',
            name='resubmission_attempt',
            field=models.IntegerField(default=1, verbose_name='提交次数'),
        ),
    ]
