# Generated by Django 5.2.4 on 2026-08-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0029_formchannel_example_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelExampleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='channel_examples/%Y/%m/', verbose_name='示例文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                (
                    'channel',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='example_files',
                        to='clubs.formchannel',
                        verbose_name='通道',
                    ),
                ),
            ],
            options={
                'verbose_name': '通道示例文件',
                'verbose_name_plural': '通道示例文件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='formchannel',
            name='example_file',
        ),
    ]
