# Generated by Django 5.2.8 on 2025-12-10 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0029_activityapplication_resubmission_attempt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityapplication',
            name='staff_approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='干事是否批准'),
        ),
        migrations.AddField(
            model_name='activityapplication',
            name='staff_comment',
            field=models.TextField(blank=True, verbose_name='干事审核意见'),
        ),
        migrations.AddField(
            model_name='activityapplication',
            name='staff_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='干事审核时间'),
        ),
        migrations.AddField(
            model_name='activityapplication',
            name='staff_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_reviewed_activities', to=settings.AUTH_USER_MODEL, verbose_name='干事审核人'),
        ),
        migrations.AddField(
            model_name='activityapplication',
            name='teacher_approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='老师是否批准'),
        ),
        migrations.AddField(
            model_name='activityapplication',
            name='teacher_comment',
            field=models.TextField(blank=True, verbose_name='老师审核意见'),
        ),
        migrations.AddField(
            model_name='activityapplication',
            name='teacher_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='老师审核时间'),
        ),
        migrations.AddField(
            model_name='activityapplication',
            name='teacher_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_reviewed_activities', to=settings.AUTH_USER_MODEL, verbose_name='老师审核人'),
        ),
        migrations.AlterField(
            model_name='activityapplication',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('staff_approved', '干事已批准'), ('teacher_approved', '老师已批准'), ('approved', '已批准'), ('rejected', '被拒绝')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
