# Generated by Django 5.2.8 on 2025-12-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0031_activityparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubregistration',
            name='resubmission_attempt',
            field=models.IntegerField(default=1, verbose_name='提交次数'),
        ),
        migrations.AddField(
            model_name='presidenttransition',
            name='resubmission_attempt',
            field=models.IntegerField(default=1, verbose_name='提交次数'),
        ),
        migrations.AddField(
            model_name='reimbursement',
            name='resubmission_attempt',
            field=models.IntegerField(default=1, verbose_name='提交次数'),
        ),
    ]
