# Generated by Django 5.2.16 on 2026-08-06 05:44

from django.conf import settings
from django.db import migrations, models


def backfill_profile_data(apps, schema_editor):
    """迁移历史数据：以 department_link 为唯一部门存储，并清理旧的审核状态值。"""
    UserProfile = apps.get_model('clubs', 'UserProfile')
    Department = apps.get_model('clubs', 'Department')

    # 老数据只写了 department 文本时，按名称回填 department_link。
    for profile in UserProfile.objects.exclude(department='').exclude(department=None):
        if profile.department_link_id:
            continue
        dept = Department.objects.filter(name=profile.department).first()
        if dept:
            profile.department_link = dept
            profile.save(update_fields=['department_link'])

    # status 只保留干事审核语义，历史误写入的 'inactive' 全部恢复为 'approved'。
    UserProfile.objects.filter(status='inactive').update(status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0032_sitesettings_low_member_alert_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_profile_data, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='registrationtoken',
            name='rt_club_exp_used_idx',
        ),
        migrations.RemoveField(
            model_name='formuploadedfile',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='registrationtoken',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='storageconfig',
            name='s3_use_path_style',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝')], default='approved', max_length=20, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='registrationtoken',
            index=models.Index(fields=['club', 'expires_at'], name='rt_club_exp_idx'),
        ),
    ]
