# Generated by Django 5.2.8 on 2025-12-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0032_add_resubmission_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsubmission',
            name='resubmission_attempt',
            field=models.IntegerField(default=1, verbose_name='提交次数'),
        ),
    ]
