# Generated by Django 5.2.16 on 2026-08-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0033_remove_registrationtoken_rt_club_exp_used_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
