# Generated by Django 5.2.16 on 2026-08-06 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# 系统内置材料模板：名称与 Template.TEMPLATE_TYPES 保持一致，
# 首次 migrate 时自动导入，之后可在后台补充文件或编辑。
DEFAULT_TEMPLATES = [
    ('年审 - 财务报告', 'review_financial'),
    ('年审 - 活动报告', 'review_activity'),
    ('年审 - 成员名单', 'review_member_list'),
    ('年审 - 自查表', 'review_self_assessment'),
    ('年审 - 社团章程', 'review_club_constitution'),
    ('年审 - 负责人学习及工作情况表', 'review_leader_report'),
    ('年审 - 社团年度活动清单', 'review_annual_activity'),
    ('年审 - 指导教师履职情况表', 'review_advisor_report'),
    ('年审 - 社团成员构成表', 'review_member_composition'),
    ('年审 - 新媒体账号及运维情况表', 'review_media_account'),
    ('报销模板', 'reimbursement'),
    ('社团申请 - 社团成立申请书', 'application_establishment'),
    ('社团申请 - 社团章程草案', 'application_constitution'),
    ('社团申请 - 社团三年发展规划', 'application_three_year_plan'),
    ('社团申请 - 负责人简历', 'application_leader_resume'),
    ('社团申请 - 指导老师简历', 'application_advisor_resume'),
    ('社团申请 - 身份证复印件', 'application_id_copies'),
    ('社团申请 - 一个月活动计划', 'application_monthly_plan'),
    ('社团申请 - 指导老师专业证书', 'application_teacher_certificates'),
    ('社团注册 - 社团注册申请表', 'registration_form'),
    ('社团注册 - 学生社团基础信息表', 'registration_basic_info'),
    ('社团注册 - 会费表', 'registration_fee_form'),
    ('社团注册 - 免收会费说明书', 'registration_fee_exemption'),
    ('社团注册 - 负责人变动申请', 'registration_leader_change'),
    ('社团注册 - 社团大会会议记录', 'registration_meeting_minutes'),
    ('社团注册 - 社团名称变更申请表', 'registration_name_change'),
    ('社团注册 - 指导老师变动申请表', 'registration_advisor_change'),
    ('社团注册 - 业务指导单位变动申请表', 'registration_business_unit_change'),
    ('社团注册 - 新媒体平台建立申请表', 'registration_social_media'),
    ('社团创建文件', 'club_creation'),
    ('社长变更申请', 'leader_change'),
]


def seed_default_templates(apps, schema_editor):
    Template = apps.get_model('clubs', 'Template')
    for name, template_type in DEFAULT_TEMPLATES:
        Template.objects.get_or_create(
            template_type=template_type,
            defaults={'name': name, 'is_active': True, 'description': ''},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0034_delete_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('template_type', models.CharField(choices=[('review_financial', '年审 - 财务报告'), ('review_activity', '年审 - 活动报告'), ('review_member_list', '年审 - 成员名单'), ('review_self_assessment', '年审 - 自查表'), ('review_club_constitution', '年审 - 社团章程'), ('review_leader_report', '年审 - 负责人学习及工作情况表'), ('review_annual_activity', '年审 - 社团年度活动清单'), ('review_advisor_report', '年审 - 指导教师履职情况表'), ('review_member_composition', '年审 - 社团成员构成表'), ('review_media_account', '年审 - 新媒体账号及运维情况表'), ('reimbursement', '报销模板'), ('application_establishment', '社团申请 - 社团成立申请书'), ('application_constitution', '社团申请 - 社团章程草案'), ('application_three_year_plan', '社团申请 - 社团三年发展规划'), ('application_leader_resume', '社团申请 - 负责人简历'), ('application_advisor_resume', '社团申请 - 指导老师简历'), ('application_id_copies', '社团申请 - 身份证复印件'), ('application_monthly_plan', '社团申请 - 一个月活动计划'), ('application_teacher_certificates', '社团申请 - 指导老师专业证书'), ('registration_form', '社团注册 - 社团注册申请表'), ('registration_basic_info', '社团注册 - 学生社团基础信息表'), ('registration_fee_form', '社团注册 - 会费表'), ('registration_fee_exemption', '社团注册 - 免收会费说明书'), ('registration_leader_change', '社团注册 - 负责人变动申请'), ('registration_meeting_minutes', '社团注册 - 社团大会会议记录'), ('registration_name_change', '社团注册 - 社团名称变更申请表'), ('registration_advisor_change', '社团注册 - 指导老师变动申请表'), ('registration_business_unit_change', '社团注册 - 业务指导单位变动申请表'), ('registration_social_media', '社团注册 - 新媒体平台建立申请表'), ('club_creation', '社团创建文件'), ('leader_change', '社长变更申请')], max_length=50, verbose_name='模板类型')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('file', models.FileField(blank=True, null=True, upload_to='templates/%Y/%m/', verbose_name='模板文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '模板',
                'verbose_name_plural': '模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_default_templates, migrations.RunPython.noop),
    ]
