# Auto-generated by scripts/i18n_wrap_templates.py
from django.utils.translation import gettext_noop

gettext_noop('暂无描述')
gettext_noop('未发布')
gettext_noop('未填写')
gettext_noop('未设置邮箱')
gettext_noop('用户管理')
gettext_noop('管理所有用户账户和权限')
gettext_noop('系统用户管理')
