"""
Django settings for CManager project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(env_path: Path):
    if not env_path.exists():
        return

    for line in env_path.read_text(encoding='utf-8-sig').splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith('#') or '=' not in stripped:
            continue

        # Support shell-style "export KEY=VALUE" entries.
        if stripped.startswith('export '):
            stripped = stripped[7:].strip()

        key, value = stripped.split('=', 1)
        cleaned = value.strip()

        # Trim inline comments for unquoted values: KEY=value # comment
        if cleaned and cleaned[0] not in ('"', "'") and ' #' in cleaned:
            cleaned = cleaned.split(' #', 1)[0].rstrip()

        os.environ.setdefault(key.strip(), cleaned.strip('"').strip("'"))


def _load_env():
    local_env_path = BASE_DIR / '.env.local'

    _load_env_file(local_env_path)


def _env_list(name, default):
    value = os.environ.get(name)
    if value is None:
        return default
    normalized = value.replace('，', ',').replace(';', ',')
    return [item.strip() for item in normalized.split(',') if item.strip()]


def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in ('1', 'true', 'yes', 'on')


def _env_int(name, default):
    raw = os.environ.get(name)
    if raw is None:
        return default
    try:
        return int(raw)
    except ValueError:
        return default


_load_env()

# Allow MySQL backend to run with PyMySQL when mysqlclient is unavailable.
if os.getenv('DB_ENGINE', '').strip() == 'django.db.backends.mysql':
    try:
        import MySQLdb  # type: ignore # noqa: F401
    except Exception:
        try:
            import pymysql  # type: ignore
            pymysql.install_as_MySQLdb()
        except Exception:
            # Keep Django's native error message if neither driver is available.
            pass


def _default_csrf_trusted_origins_from_hosts(hosts):
    origins = []
    for host in hosts:
        if not host or host == '*':
            continue
        host = host.strip()
        if host.startswith('.'):
            host = host[1:]
        if not host:
            continue
        origins.append(f'https://{host}')
        origins.append(f'http://{host}')

    # Keep loopback defaults for local debugging.
    if 'http://127.0.0.1' not in origins:
        origins.append('http://127.0.0.1')
    if 'http://localhost' not in origins:
        origins.append('http://localhost')
    return origins

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'unsafe-secret-key')
CREDENTIAL_ENCRYPTION_KEY = os.environ.get('CREDENTIAL_ENCRYPTION_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', False)
ALLOW_DERIVED_CREDENTIAL_KEY = DEBUG or 'test' in sys.argv

if not DEBUG and (
    not SECRET_KEY
    or len(SECRET_KEY) < 32
    or SECRET_KEY in {'unsafe-secret-key', 'your_secret_key_here'}
):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured('生产环境必须通过 SECRET_KEY 环境变量设置足够强度的密钥')

ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', ['localhost', '127.0.0.1'])

# CSRF信任源，用于解决反向代理环境下的CSRF验证问题
CSRF_TRUSTED_ORIGINS = _env_list(
    'CSRF_TRUSTED_ORIGINS',
    _default_csrf_trusted_origins_from_hosts(ALLOWED_HOSTS),
)

# 反向代理主开关：仅在 Nginx/Caddy/Traefik 等反代部署时设为 True。
# 直连端口部署必须保持 False，否则会信任客户端伪造的代理头。
IS_NGINX_PROXY = _env_bool('IS_NGINX_PROXY', False)

# 生产环境安全设置
SECURE_BROWSER_XSS_FILTER = _env_bool('SECURE_BROWSER_XSS_FILTER', True)
SECURE_CONTENT_TYPE_NOSNIFF = _env_bool('SECURE_CONTENT_TYPE_NOSNIFF', True)
# Django 默认不直接提供 HTTPS，HTTPS 必须由 Nginx 反代终止 TLS。
# 因此以下 HTTPS 强制措施仅在 IS_NGINX_PROXY=True 时开启：
# - secure cookie：直连 HTTP 部署时开启会导致登录态失效
# - SSL 跳转：直连 HTTP 部署时开启会造成跳转死循环
# - HSTS：仅对 HTTPS 站点有意义
SESSION_COOKIE_SECURE = IS_NGINX_PROXY and _env_bool('SESSION_COOKIE_SECURE', True)
CSRF_COOKIE_SECURE = IS_NGINX_PROXY and _env_bool('CSRF_COOKIE_SECURE', True)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax')
SECURE_SSL_REDIRECT = IS_NGINX_PROXY and _env_bool('SECURE_SSL_REDIRECT', True)
SECURE_HSTS_SECONDS = 0 if not IS_NGINX_PROXY else _env_int('SECURE_HSTS_SECONDS', 31536000)
SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_NGINX_PROXY and _env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
SECURE_HSTS_PRELOAD = IS_NGINX_PROXY and _env_bool('SECURE_HSTS_PRELOAD', True)
X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')

USE_X_FORWARDED_HOST = IS_NGINX_PROXY and _env_bool('USE_X_FORWARDED_HOST', False)
USE_X_FORWARDED_PORT = IS_NGINX_PROXY and _env_bool('USE_X_FORWARDED_PORT', False)
# 反代会把真实客户端 IP 追加到 X-Forwarded-For 末尾；仅在主开关开启时生效。
USE_X_FORWARDED_FOR = IS_NGINX_PROXY and _env_bool('USE_X_FORWARDED_FOR', True)
USE_X_FORWARDED_PROTO = IS_NGINX_PROXY and _env_bool('USE_X_FORWARDED_PROTO', True)
if USE_X_FORWARDED_PROTO:
    forwarded_proto_header = os.getenv('FORWARDED_PROTO_HEADER', 'HTTP_X_FORWARDED_PROTO').strip()
    forwarded_proto_value = os.getenv('FORWARDED_PROTO_VALUE', 'https').strip() or 'https'
    SECURE_PROXY_SSL_HEADER = (forwarded_proto_header, forwarded_proto_value)

# 静态文件配置
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'clubs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'CManager.middleware.ClientFileMd5Middleware',
    'CManager.middleware.PartialRenderMiddleware',
    'CManager.middleware.InitialSetupMiddleware',
    'CManager.middleware.VisitTrackingMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.http.ConditionalGetMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CManager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'clubs.context_processors.unread_approvals',
                'clubs.context_processors.site_settings',
                'clubs.context_processors.base_template',
            ],
        },
    },
]

if not DEBUG:
    TEMPLATES[0]['APP_DIRS'] = False
    TEMPLATES[0]['OPTIONS']['loaders'] = [
        (
            'django.template.loaders.cached.Loader',
            [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        )
    ]

WSGI_APPLICATION = 'CManager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

default_db_engine = os.getenv('DB_ENGINE', 'django.db.backends.dummy')
default_db_name = os.getenv('DB_NAME', '')
if default_db_engine == 'django.db.backends.sqlite3' and not default_db_name:
    default_db_name = str(BASE_DIR / 'db.sqlite3')

DATABASES = {
    'default': {
        'ENGINE': default_db_engine,
        'NAME': default_db_name,
        'CONN_MAX_AGE': _env_int('DB_CONN_MAX_AGE', 60),
    }
}

if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    DATABASES['default']['CONN_MAX_AGE'] = _env_int('SQLITE_CONN_MAX_AGE', _env_int('DB_CONN_MAX_AGE', 60))
    DATABASES['default']['OPTIONS'] = {
        'timeout': _env_int('SQLITE_TIMEOUT', 30),
        'init_command': (
            f"PRAGMA journal_mode=WAL; "
            f"PRAGMA synchronous={os.getenv('SQLITE_SYNCHRONOUS', 'NORMAL')}; "
            f"PRAGMA temp_store=MEMORY; "
            f"PRAGMA cache_size={_env_int('SQLITE_CACHE_SIZE', -20000)}; "
            f"PRAGMA mmap_size={_env_int('SQLITE_MMAP_SIZE', 134217728)};"
        ),
    }

if os.getenv('DB_USER'):
    DATABASES['default']['USER'] = os.getenv('DB_USER')

if os.getenv('DB_PASSWORD'):
    DATABASES['default']['PASSWORD'] = os.getenv('DB_PASSWORD')

if os.getenv('DB_HOST'):
    DATABASES['default']['HOST'] = os.getenv('DB_HOST')

if os.getenv('DB_PORT'):
    DATABASES['default']['PORT'] = os.getenv('DB_PORT')


# Cache（高并发下优先减少重复查询/渲染开销）
CACHE_BACKEND = os.getenv('CACHE_BACKEND', 'locmem').strip().lower()

if CACHE_BACKEND == 'filebased':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
            'LOCATION': str(BASE_DIR / '.cache' / 'django'),
            'TIMEOUT': _env_int('CACHE_TIMEOUT', 300),
            'KEY_PREFIX': os.getenv('CACHE_KEY_PREFIX', 'cmanager'),
        }
    }
elif CACHE_BACKEND == 'dummy':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
elif CACHE_BACKEND == 'redis':
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
            'KEY_PREFIX': os.getenv('CACHE_KEY_PREFIX', 'cmanager'),
            'TIMEOUT': _env_int('CACHE_TIMEOUT', 300),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': os.getenv('CACHE_LOCATION', 'cmanager-default-cache'),
            'TIMEOUT': _env_int('CACHE_TIMEOUT', 300),
            'KEY_PREFIX': os.getenv('CACHE_KEY_PREFIX', 'cmanager'),
        }
    }

if not DEBUG:
    if SECRET_KEY == 'unsafe-secret-key' or len(SECRET_KEY) < 32:
        raise RuntimeError('生产环境必须设置长度至少为 32 的 SECRET_KEY')
    if not CREDENTIAL_ENCRYPTION_KEY:
        raise RuntimeError('生产环境必须设置 CREDENTIAL_ENCRYPTION_KEY')
    if IS_NGINX_PROXY and not (SESSION_COOKIE_SECURE and CSRF_COOKIE_SECURE):
        raise RuntimeError(
            '使用 Nginx 反向代理（IS_NGINX_PROXY=True）时必须启用 SESSION_COOKIE_SECURE 和 CSRF_COOKIE_SECURE'
        )
    if CACHE_BACKEND != 'redis' and not _env_bool('ALLOW_NON_REDIS_CACHE', False):
        raise RuntimeError('生产环境必须使用 Redis 缓存；仅测试环境可设置 ALLOW_NON_REDIS_CACHE=True')

if DATABASES['default']['ENGINE'] == 'django.db.backends.dummy':
    SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
elif (BASE_DIR / '.oobe_pending.json').exists():
    # During bootstrap, avoid session-table dependency before migrations settle.
    SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
elif _env_bool('SESSION_USE_CACHED_DB', True):
    SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
    SESSION_CACHE_ALIAS = 'default'

# 并发调优参数 - 访问统计批量写入 & 初始化检测缓存
VISIT_STAT_FLUSH_INTERVAL = _env_int('VISIT_STAT_FLUSH_INTERVAL', 20)
VISIT_STAT_FLUSH_LOCK_SECONDS = _env_int('VISIT_STAT_FLUSH_LOCK_SECONDS', 5)
INITIAL_SETUP_CACHE_SECONDS = _env_int('INITIAL_SETUP_CACHE_SECONDS', 30)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

# 多语言：简体中文（源语言，msgid 即中文）、English、维吾尔语（RTL）、蒙古语（西里尔）。
# 语言通过 django_language Cookie 切换，未设置时回退到浏览器 Accept-Language。
LANGUAGES = [
    ('zh-hans', '简体中文'),
    ('en', 'English'),
    ('ug', 'ئۇيغۇرچە'),
    ('mn', 'Монгол'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
SECURE_RANDOMIZE_UPLOAD_NAMES = _env_bool('SECURE_RANDOMIZE_UPLOAD_NAMES', True)

# 存储：通过抽象层 ClubStorage 实现 Local / S3 后端动态切换
# 业务代码所有 FileField 自动走该 storage；切换后端时只需修改 StorageConfig 表
STORAGES = {
    "default": {
        "BACKEND": "clubs.storage_backends.ClubStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 登录URL设置
LOGIN_URL = 'clubs:login'

# 管理员联系邮箱（登录锁定时用于显示联系按钮）
ADMIN_CONTACT_EMAIL = os.getenv('ADMIN_CONTACT_EMAIL', 'admin@example.com')

# Email 设置（开发环境使用控制台后台，生产请配置真实 SMTP）
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.example.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'no-reply@example.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', True)
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@example.com')
